[Sat Apr 18 14:06:45.573055 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00292: Apache/2.4.41 (Unix) mod_wsgi/4.7.1 Python/3.7 configured -- resuming normal operations
[Sat Apr 18 14:06:45.573228 2020] [core:notice] [pid 32761:tid 139940535924608] AH00094: Command line: '/home/dvateam128/webapps/team128_app/apache2/bin/httpd.worker -f /home/dvateam128/webapps/team128_app/apache2/conf/httpd.conf'
[Sat Apr 18 15:27:23.633474 2020] [wsgi:error] [pid 32764:tid 139940455544576] [remote 127.0.0.1:46874] Not Found: /static/admin/css/fonts.css
[Sat Apr 18 15:28:26.509022 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00298: SIGHUP received.  Attempting to restart
[Sat Apr 18 15:28:26.710853 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00292: Apache/2.4.41 (Unix) mod_wsgi/4.7.1 Python/3.7 configured -- resuming normal operations
[Sat Apr 18 15:28:26.710877 2020] [core:notice] [pid 32761:tid 139940535924608] AH00094: Command line: '/home/dvateam128/webapps/team128_app/apache2/bin/httpd.worker -f /home/dvateam128/webapps/team128_app/apache2/conf/httpd.conf'
[Sat Apr 18 15:28:28.847868 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:56926] mod_wsgi (pid=21663): Failed to exec Python script file '/home/dvateam128/webapps/team128_app/server/server/wsgi.py'.
[Sat Apr 18 15:28:28.847945 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:56926] mod_wsgi (pid=21663): Exception occurred processing WSGI script '/home/dvateam128/webapps/team128_app/server/server/wsgi.py'.
[Sat Apr 18 15:28:28.848851 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:56926] Traceback (most recent call last):
[Sat Apr 18 15:28:28.848906 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:56926]   File "/home/dvateam128/webapps/team128_app/server/server/wsgi.py", line 16, in <module>
[Sat Apr 18 15:28:28.848912 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:56926]     application = get_wsgi_application()
[Sat Apr 18 15:28:28.848918 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:56926]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/wsgi.py", line 12, in get_wsgi_application
[Sat Apr 18 15:28:28.848922 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:56926]     django.setup(set_prefix=False)
[Sat Apr 18 15:28:28.848928 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:56926]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/__init__.py", line 19, in setup
[Sat Apr 18 15:28:28.848932 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:56926]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Sat Apr 18 15:28:28.848937 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:56926]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/conf/__init__.py", line 79, in __getattr__
[Sat Apr 18 15:28:28.848941 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:56926]     self._setup(name)
[Sat Apr 18 15:28:28.848946 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:56926]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/conf/__init__.py", line 66, in _setup
[Sat Apr 18 15:28:28.848950 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:56926]     self._wrapped = Settings(settings_module)
[Sat Apr 18 15:28:28.848955 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:56926]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/conf/__init__.py", line 157, in __init__
[Sat Apr 18 15:28:28.848958 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:56926]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Sat Apr 18 15:28:28.848963 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:56926]   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
[Sat Apr 18 15:28:28.848973 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:56926]     return _bootstrap._gcd_import(name[level:], package, level)
[Sat Apr 18 15:28:28.848979 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:56926]   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
[Sat Apr 18 15:28:28.848984 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:56926]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[Sat Apr 18 15:28:28.848989 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:56926]   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
[Sat Apr 18 15:28:28.849007 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:56926] ModuleNotFoundError: No module named 'server.settings'
[Sat Apr 18 15:29:24.792694 2020] [wsgi:error] [pid 21662:tid 139940455544576] [remote 127.0.0.1:37670] mod_wsgi (pid=21662): Failed to exec Python script file '/home/dvateam128/webapps/team128_app/server/server/wsgi.py'.
[Sat Apr 18 15:29:24.792784 2020] [wsgi:error] [pid 21662:tid 139940455544576] [remote 127.0.0.1:37670] mod_wsgi (pid=21662): Exception occurred processing WSGI script '/home/dvateam128/webapps/team128_app/server/server/wsgi.py'.
[Sat Apr 18 15:29:24.793526 2020] [wsgi:error] [pid 21662:tid 139940455544576] [remote 127.0.0.1:37670] Traceback (most recent call last):
[Sat Apr 18 15:29:24.793597 2020] [wsgi:error] [pid 21662:tid 139940455544576] [remote 127.0.0.1:37670]   File "/home/dvateam128/webapps/team128_app/server/server/wsgi.py", line 16, in <module>
[Sat Apr 18 15:29:24.793603 2020] [wsgi:error] [pid 21662:tid 139940455544576] [remote 127.0.0.1:37670]     application = get_wsgi_application()
[Sat Apr 18 15:29:24.793611 2020] [wsgi:error] [pid 21662:tid 139940455544576] [remote 127.0.0.1:37670]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/wsgi.py", line 12, in get_wsgi_application
[Sat Apr 18 15:29:24.793615 2020] [wsgi:error] [pid 21662:tid 139940455544576] [remote 127.0.0.1:37670]     django.setup(set_prefix=False)
[Sat Apr 18 15:29:24.793622 2020] [wsgi:error] [pid 21662:tid 139940455544576] [remote 127.0.0.1:37670]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/__init__.py", line 19, in setup
[Sat Apr 18 15:29:24.793626 2020] [wsgi:error] [pid 21662:tid 139940455544576] [remote 127.0.0.1:37670]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Sat Apr 18 15:29:24.793632 2020] [wsgi:error] [pid 21662:tid 139940455544576] [remote 127.0.0.1:37670]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/conf/__init__.py", line 79, in __getattr__
[Sat Apr 18 15:29:24.793636 2020] [wsgi:error] [pid 21662:tid 139940455544576] [remote 127.0.0.1:37670]     self._setup(name)
[Sat Apr 18 15:29:24.793642 2020] [wsgi:error] [pid 21662:tid 139940455544576] [remote 127.0.0.1:37670]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/conf/__init__.py", line 66, in _setup
[Sat Apr 18 15:29:24.793646 2020] [wsgi:error] [pid 21662:tid 139940455544576] [remote 127.0.0.1:37670]     self._wrapped = Settings(settings_module)
[Sat Apr 18 15:29:24.793652 2020] [wsgi:error] [pid 21662:tid 139940455544576] [remote 127.0.0.1:37670]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/conf/__init__.py", line 157, in __init__
[Sat Apr 18 15:29:24.793656 2020] [wsgi:error] [pid 21662:tid 139940455544576] [remote 127.0.0.1:37670]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Sat Apr 18 15:29:24.793662 2020] [wsgi:error] [pid 21662:tid 139940455544576] [remote 127.0.0.1:37670]   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
[Sat Apr 18 15:29:24.793666 2020] [wsgi:error] [pid 21662:tid 139940455544576] [remote 127.0.0.1:37670]     return _bootstrap._gcd_import(name[level:], package, level)
[Sat Apr 18 15:29:24.793671 2020] [wsgi:error] [pid 21662:tid 139940455544576] [remote 127.0.0.1:37670]   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
[Sat Apr 18 15:29:24.793690 2020] [wsgi:error] [pid 21662:tid 139940455544576] [remote 127.0.0.1:37670]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[Sat Apr 18 15:29:24.793696 2020] [wsgi:error] [pid 21662:tid 139940455544576] [remote 127.0.0.1:37670]   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
[Sat Apr 18 15:29:24.793716 2020] [wsgi:error] [pid 21662:tid 139940455544576] [remote 127.0.0.1:37670] ModuleNotFoundError: No module named 'server.settings'
[Sat Apr 18 15:31:27.888180 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59142] mod_wsgi (pid=21663): Failed to exec Python script file '/home/dvateam128/webapps/team128_app/server/server/wsgi.py'.
[Sat Apr 18 15:31:27.888260 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59142] mod_wsgi (pid=21663): Exception occurred processing WSGI script '/home/dvateam128/webapps/team128_app/server/server/wsgi.py'.
[Sat Apr 18 15:31:27.888477 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59142] Traceback (most recent call last):
[Sat Apr 18 15:31:27.888548 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59142]   File "/home/dvateam128/webapps/team128_app/server/server/wsgi.py", line 16, in <module>
[Sat Apr 18 15:31:27.888554 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59142]     application = get_wsgi_application()
[Sat Apr 18 15:31:27.888562 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59142]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/wsgi.py", line 12, in get_wsgi_application
[Sat Apr 18 15:31:27.888567 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59142]     django.setup(set_prefix=False)
[Sat Apr 18 15:31:27.888574 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59142]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/__init__.py", line 19, in setup
[Sat Apr 18 15:31:27.888579 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59142]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Sat Apr 18 15:31:27.888586 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59142]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/conf/__init__.py", line 79, in __getattr__
[Sat Apr 18 15:31:27.888591 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59142]     self._setup(name)
[Sat Apr 18 15:31:27.888597 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59142]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/conf/__init__.py", line 66, in _setup
[Sat Apr 18 15:31:27.888601 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59142]     self._wrapped = Settings(settings_module)
[Sat Apr 18 15:31:27.888608 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59142]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/conf/__init__.py", line 157, in __init__
[Sat Apr 18 15:31:27.888612 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59142]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Sat Apr 18 15:31:27.888618 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59142]   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
[Sat Apr 18 15:31:27.888623 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59142]     return _bootstrap._gcd_import(name[level:], package, level)
[Sat Apr 18 15:31:27.888629 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59142]   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
[Sat Apr 18 15:31:27.888635 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59142]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[Sat Apr 18 15:31:27.888658 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59142]   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
[Sat Apr 18 15:31:27.888682 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59142] ModuleNotFoundError: No module named 'server.settings'
[Sat Apr 18 15:34:23.492870 2020] [wsgi:error] [pid 21662:tid 139940363224832] [remote 127.0.0.1:59598] mod_wsgi (pid=21662): Failed to exec Python script file '/home/dvateam128/webapps/team128_app/server/server/wsgi.py'.
[Sat Apr 18 15:34:23.492961 2020] [wsgi:error] [pid 21662:tid 139940363224832] [remote 127.0.0.1:59598] mod_wsgi (pid=21662): Exception occurred processing WSGI script '/home/dvateam128/webapps/team128_app/server/server/wsgi.py'.
[Sat Apr 18 15:34:23.493201 2020] [wsgi:error] [pid 21662:tid 139940363224832] [remote 127.0.0.1:59598] Traceback (most recent call last):
[Sat Apr 18 15:34:23.493282 2020] [wsgi:error] [pid 21662:tid 139940363224832] [remote 127.0.0.1:59598]   File "/home/dvateam128/webapps/team128_app/server/server/wsgi.py", line 16, in <module>
[Sat Apr 18 15:34:23.493290 2020] [wsgi:error] [pid 21662:tid 139940363224832] [remote 127.0.0.1:59598]     application = get_wsgi_application()
[Sat Apr 18 15:34:23.493299 2020] [wsgi:error] [pid 21662:tid 139940363224832] [remote 127.0.0.1:59598]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/wsgi.py", line 12, in get_wsgi_application
[Sat Apr 18 15:34:23.493306 2020] [wsgi:error] [pid 21662:tid 139940363224832] [remote 127.0.0.1:59598]     django.setup(set_prefix=False)
[Sat Apr 18 15:34:23.493314 2020] [wsgi:error] [pid 21662:tid 139940363224832] [remote 127.0.0.1:59598]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/__init__.py", line 19, in setup
[Sat Apr 18 15:34:23.493320 2020] [wsgi:error] [pid 21662:tid 139940363224832] [remote 127.0.0.1:59598]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Sat Apr 18 15:34:23.493328 2020] [wsgi:error] [pid 21662:tid 139940363224832] [remote 127.0.0.1:59598]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/conf/__init__.py", line 79, in __getattr__
[Sat Apr 18 15:34:23.493334 2020] [wsgi:error] [pid 21662:tid 139940363224832] [remote 127.0.0.1:59598]     self._setup(name)
[Sat Apr 18 15:34:23.493342 2020] [wsgi:error] [pid 21662:tid 139940363224832] [remote 127.0.0.1:59598]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/conf/__init__.py", line 66, in _setup
[Sat Apr 18 15:34:23.493348 2020] [wsgi:error] [pid 21662:tid 139940363224832] [remote 127.0.0.1:59598]     self._wrapped = Settings(settings_module)
[Sat Apr 18 15:34:23.493356 2020] [wsgi:error] [pid 21662:tid 139940363224832] [remote 127.0.0.1:59598]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/conf/__init__.py", line 157, in __init__
[Sat Apr 18 15:34:23.493361 2020] [wsgi:error] [pid 21662:tid 139940363224832] [remote 127.0.0.1:59598]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Sat Apr 18 15:34:23.493369 2020] [wsgi:error] [pid 21662:tid 139940363224832] [remote 127.0.0.1:59598]   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
[Sat Apr 18 15:34:23.493374 2020] [wsgi:error] [pid 21662:tid 139940363224832] [remote 127.0.0.1:59598]     return _bootstrap._gcd_import(name[level:], package, level)
[Sat Apr 18 15:34:23.493382 2020] [wsgi:error] [pid 21662:tid 139940363224832] [remote 127.0.0.1:59598]   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
[Sat Apr 18 15:34:23.493391 2020] [wsgi:error] [pid 21662:tid 139940363224832] [remote 127.0.0.1:59598]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[Sat Apr 18 15:34:23.493399 2020] [wsgi:error] [pid 21662:tid 139940363224832] [remote 127.0.0.1:59598]   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
[Sat Apr 18 15:34:23.493441 2020] [wsgi:error] [pid 21662:tid 139940363224832] [remote 127.0.0.1:59598] ModuleNotFoundError: No module named 'server.settings'
[Sat Apr 18 15:34:23.598832 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:59604] mod_wsgi (pid=21663): Failed to exec Python script file '/home/dvateam128/webapps/team128_app/server/server/wsgi.py'.
[Sat Apr 18 15:34:23.598890 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:59604] mod_wsgi (pid=21663): Exception occurred processing WSGI script '/home/dvateam128/webapps/team128_app/server/server/wsgi.py'.
[Sat Apr 18 15:34:23.599071 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:59604] Traceback (most recent call last):
[Sat Apr 18 15:34:23.599129 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:59604]   File "/home/dvateam128/webapps/team128_app/server/server/wsgi.py", line 16, in <module>
[Sat Apr 18 15:34:23.599135 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:59604]     application = get_wsgi_application()
[Sat Apr 18 15:34:23.599142 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:59604]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/wsgi.py", line 12, in get_wsgi_application
[Sat Apr 18 15:34:23.599146 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:59604]     django.setup(set_prefix=False)
[Sat Apr 18 15:34:23.599153 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:59604]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/__init__.py", line 19, in setup
[Sat Apr 18 15:34:23.599157 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:59604]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Sat Apr 18 15:34:23.599163 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:59604]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/conf/__init__.py", line 79, in __getattr__
[Sat Apr 18 15:34:23.599167 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:59604]     self._setup(name)
[Sat Apr 18 15:34:23.599173 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:59604]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/conf/__init__.py", line 66, in _setup
[Sat Apr 18 15:34:23.599177 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:59604]     self._wrapped = Settings(settings_module)
[Sat Apr 18 15:34:23.599182 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:59604]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/conf/__init__.py", line 157, in __init__
[Sat Apr 18 15:34:23.599186 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:59604]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Sat Apr 18 15:34:23.599192 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:59604]   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
[Sat Apr 18 15:34:23.599196 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:59604]     return _bootstrap._gcd_import(name[level:], package, level)
[Sat Apr 18 15:34:23.599202 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:59604]   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
[Sat Apr 18 15:34:23.599207 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:59604]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[Sat Apr 18 15:34:23.599213 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:59604]   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
[Sat Apr 18 15:34:23.599232 2020] [wsgi:error] [pid 21663:tid 139940455544576] [remote 127.0.0.1:59604] ModuleNotFoundError: No module named 'server.settings'
[Sat Apr 18 15:34:24.413463 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59752] mod_wsgi (pid=21663): Failed to exec Python script file '/home/dvateam128/webapps/team128_app/server/server/wsgi.py'.
[Sat Apr 18 15:34:24.413542 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59752] mod_wsgi (pid=21663): Exception occurred processing WSGI script '/home/dvateam128/webapps/team128_app/server/server/wsgi.py'.
[Sat Apr 18 15:34:24.413745 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59752] Traceback (most recent call last):
[Sat Apr 18 15:34:24.414681 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59752]   File "/home/dvateam128/webapps/team128_app/server/server/wsgi.py", line 16, in <module>
[Sat Apr 18 15:34:24.414906 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59752]     application = get_wsgi_application()
[Sat Apr 18 15:34:24.414918 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59752]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/wsgi.py", line 12, in get_wsgi_application
[Sat Apr 18 15:34:24.414924 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59752]     django.setup(set_prefix=False)
[Sat Apr 18 15:34:24.414932 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59752]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/__init__.py", line 19, in setup
[Sat Apr 18 15:34:24.415140 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59752]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Sat Apr 18 15:34:24.415150 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59752]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/conf/__init__.py", line 79, in __getattr__
[Sat Apr 18 15:34:24.415155 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59752]     self._setup(name)
[Sat Apr 18 15:34:24.415163 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59752]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/conf/__init__.py", line 66, in _setup
[Sat Apr 18 15:34:24.415168 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59752]     self._wrapped = Settings(settings_module)
[Sat Apr 18 15:34:24.415175 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59752]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/conf/__init__.py", line 157, in __init__
[Sat Apr 18 15:34:24.415180 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59752]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Sat Apr 18 15:34:24.415187 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59752]   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
[Sat Apr 18 15:34:24.415192 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59752]     return _bootstrap._gcd_import(name[level:], package, level)
[Sat Apr 18 15:34:24.415199 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59752]   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
[Sat Apr 18 15:34:24.415206 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59752]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[Sat Apr 18 15:34:24.415214 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59752]   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
[Sat Apr 18 15:34:24.415238 2020] [wsgi:error] [pid 21663:tid 139940293732096] [remote 127.0.0.1:59752] ModuleNotFoundError: No module named 'server.settings'
[Sat Apr 18 15:34:48.169735 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00298: SIGHUP received.  Attempting to restart
[Sat Apr 18 15:34:48.369123 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00292: Apache/2.4.41 (Unix) mod_wsgi/4.7.1 Python/3.7 configured -- resuming normal operations
[Sat Apr 18 15:34:48.369171 2020] [core:notice] [pid 32761:tid 139940535924608] AH00094: Command line: '/home/dvateam128/webapps/team128_app/apache2/bin/httpd.worker -f /home/dvateam128/webapps/team128_app/apache2/conf/httpd.conf'
[Sat Apr 18 15:34:54.968784 2020] [wsgi:error] [pid 2794:tid 139940455544576] [remote 127.0.0.1:36048] Not Found: /static/admin/css/fonts.css
[Sat Apr 18 15:35:39.399494 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00298: SIGHUP received.  Attempting to restart
[Sat Apr 18 15:35:39.601463 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00292: Apache/2.4.41 (Unix) mod_wsgi/4.7.1 Python/3.7 configured -- resuming normal operations
[Sat Apr 18 15:35:39.601498 2020] [core:notice] [pid 32761:tid 139940535924608] AH00094: Command line: '/home/dvateam128/webapps/team128_app/apache2/bin/httpd.worker -f /home/dvateam128/webapps/team128_app/apache2/conf/httpd.conf'
[Sat Apr 18 15:35:41.710117 2020] [wsgi:error] [pid 6502:tid 139940455544576] [remote 127.0.0.1:43682] mod_wsgi (pid=6502): Failed to exec Python script file '/home/dvateam128/webapps/team128_app/server/server/wsgi.py'.
[Sat Apr 18 15:35:41.710207 2020] [wsgi:error] [pid 6502:tid 139940455544576] [remote 127.0.0.1:43682] mod_wsgi (pid=6502): Exception occurred processing WSGI script '/home/dvateam128/webapps/team128_app/server/server/wsgi.py'.
[Sat Apr 18 15:35:41.710864 2020] [wsgi:error] [pid 6502:tid 139940455544576] [remote 127.0.0.1:43682] Traceback (most recent call last):
[Sat Apr 18 15:35:41.710922 2020] [wsgi:error] [pid 6502:tid 139940455544576] [remote 127.0.0.1:43682]   File "/home/dvateam128/webapps/team128_app/server/server/wsgi.py", line 16, in <module>
[Sat Apr 18 15:35:41.710929 2020] [wsgi:error] [pid 6502:tid 139940455544576] [remote 127.0.0.1:43682]     application = get_wsgi_application()
[Sat Apr 18 15:35:41.710935 2020] [wsgi:error] [pid 6502:tid 139940455544576] [remote 127.0.0.1:43682]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/wsgi.py", line 12, in get_wsgi_application
[Sat Apr 18 15:35:41.710939 2020] [wsgi:error] [pid 6502:tid 139940455544576] [remote 127.0.0.1:43682]     django.setup(set_prefix=False)
[Sat Apr 18 15:35:41.710945 2020] [wsgi:error] [pid 6502:tid 139940455544576] [remote 127.0.0.1:43682]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/__init__.py", line 19, in setup
[Sat Apr 18 15:35:41.710949 2020] [wsgi:error] [pid 6502:tid 139940455544576] [remote 127.0.0.1:43682]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Sat Apr 18 15:35:41.710954 2020] [wsgi:error] [pid 6502:tid 139940455544576] [remote 127.0.0.1:43682]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/conf/__init__.py", line 79, in __getattr__
[Sat Apr 18 15:35:41.710958 2020] [wsgi:error] [pid 6502:tid 139940455544576] [remote 127.0.0.1:43682]     self._setup(name)
[Sat Apr 18 15:35:41.710963 2020] [wsgi:error] [pid 6502:tid 139940455544576] [remote 127.0.0.1:43682]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/conf/__init__.py", line 66, in _setup
[Sat Apr 18 15:35:41.710967 2020] [wsgi:error] [pid 6502:tid 139940455544576] [remote 127.0.0.1:43682]     self._wrapped = Settings(settings_module)
[Sat Apr 18 15:35:41.710972 2020] [wsgi:error] [pid 6502:tid 139940455544576] [remote 127.0.0.1:43682]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/conf/__init__.py", line 157, in __init__
[Sat Apr 18 15:35:41.710976 2020] [wsgi:error] [pid 6502:tid 139940455544576] [remote 127.0.0.1:43682]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Sat Apr 18 15:35:41.710981 2020] [wsgi:error] [pid 6502:tid 139940455544576] [remote 127.0.0.1:43682]   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
[Sat Apr 18 15:35:41.710984 2020] [wsgi:error] [pid 6502:tid 139940455544576] [remote 127.0.0.1:43682]     return _bootstrap._gcd_import(name[level:], package, level)
[Sat Apr 18 15:35:41.711003 2020] [wsgi:error] [pid 6502:tid 139940455544576] [remote 127.0.0.1:43682]   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
[Sat Apr 18 15:35:41.711009 2020] [wsgi:error] [pid 6502:tid 139940455544576] [remote 127.0.0.1:43682]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[Sat Apr 18 15:35:41.711014 2020] [wsgi:error] [pid 6502:tid 139940455544576] [remote 127.0.0.1:43682]   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
[Sat Apr 18 15:35:41.711031 2020] [wsgi:error] [pid 6502:tid 139940455544576] [remote 127.0.0.1:43682] ModuleNotFoundError: No module named 'server.settings'
[Sat Apr 18 22:10:39.553251 2020] [wsgi:error] [pid 6500:tid 139940455544576] [remote 127.0.0.1:60452] mod_wsgi (pid=6500): Failed to exec Python script file '/home/dvateam128/webapps/team128_app/server/server/wsgi.py'.
[Sat Apr 18 22:10:39.553537 2020] [wsgi:error] [pid 6500:tid 139940455544576] [remote 127.0.0.1:60452] mod_wsgi (pid=6500): Exception occurred processing WSGI script '/home/dvateam128/webapps/team128_app/server/server/wsgi.py'.
[Sat Apr 18 22:10:39.560254 2020] [wsgi:error] [pid 6500:tid 139940455544576] [remote 127.0.0.1:60452] Traceback (most recent call last):
[Sat Apr 18 22:10:39.560358 2020] [wsgi:error] [pid 6500:tid 139940455544576] [remote 127.0.0.1:60452]   File "/home/dvateam128/webapps/team128_app/server/server/wsgi.py", line 16, in <module>
[Sat Apr 18 22:10:39.560369 2020] [wsgi:error] [pid 6500:tid 139940455544576] [remote 127.0.0.1:60452]     application = get_wsgi_application()
[Sat Apr 18 22:10:39.560380 2020] [wsgi:error] [pid 6500:tid 139940455544576] [remote 127.0.0.1:60452]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/wsgi.py", line 12, in get_wsgi_application
[Sat Apr 18 22:10:39.560387 2020] [wsgi:error] [pid 6500:tid 139940455544576] [remote 127.0.0.1:60452]     django.setup(set_prefix=False)
[Sat Apr 18 22:10:39.560397 2020] [wsgi:error] [pid 6500:tid 139940455544576] [remote 127.0.0.1:60452]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/__init__.py", line 19, in setup
[Sat Apr 18 22:10:39.560404 2020] [wsgi:error] [pid 6500:tid 139940455544576] [remote 127.0.0.1:60452]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Sat Apr 18 22:10:39.560413 2020] [wsgi:error] [pid 6500:tid 139940455544576] [remote 127.0.0.1:60452]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/conf/__init__.py", line 79, in __getattr__
[Sat Apr 18 22:10:39.560420 2020] [wsgi:error] [pid 6500:tid 139940455544576] [remote 127.0.0.1:60452]     self._setup(name)
[Sat Apr 18 22:10:39.560429 2020] [wsgi:error] [pid 6500:tid 139940455544576] [remote 127.0.0.1:60452]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/conf/__init__.py", line 66, in _setup
[Sat Apr 18 22:10:39.560436 2020] [wsgi:error] [pid 6500:tid 139940455544576] [remote 127.0.0.1:60452]     self._wrapped = Settings(settings_module)
[Sat Apr 18 22:10:39.560445 2020] [wsgi:error] [pid 6500:tid 139940455544576] [remote 127.0.0.1:60452]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/conf/__init__.py", line 157, in __init__
[Sat Apr 18 22:10:39.560451 2020] [wsgi:error] [pid 6500:tid 139940455544576] [remote 127.0.0.1:60452]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Sat Apr 18 22:10:39.560461 2020] [wsgi:error] [pid 6500:tid 139940455544576] [remote 127.0.0.1:60452]   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
[Sat Apr 18 22:10:39.560467 2020] [wsgi:error] [pid 6500:tid 139940455544576] [remote 127.0.0.1:60452]     return _bootstrap._gcd_import(name[level:], package, level)
[Sat Apr 18 22:10:39.560476 2020] [wsgi:error] [pid 6500:tid 139940455544576] [remote 127.0.0.1:60452]   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
[Sat Apr 18 22:10:39.560498 2020] [wsgi:error] [pid 6500:tid 139940455544576] [remote 127.0.0.1:60452]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[Sat Apr 18 22:10:39.560508 2020] [wsgi:error] [pid 6500:tid 139940455544576] [remote 127.0.0.1:60452]   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
[Sat Apr 18 22:10:39.560541 2020] [wsgi:error] [pid 6500:tid 139940455544576] [remote 127.0.0.1:60452] ModuleNotFoundError: No module named 'server.settings'
[Sat Apr 18 22:15:44.198518 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00298: SIGHUP received.  Attempting to restart
[Sat Apr 18 22:15:44.402825 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00292: Apache/2.4.41 (Unix) mod_wsgi/4.7.1 Python/3.7 configured -- resuming normal operations
[Sat Apr 18 22:15:44.403079 2020] [core:notice] [pid 32761:tid 139940535924608] AH00094: Command line: '/home/dvateam128/webapps/team128_app/apache2/bin/httpd.worker -f /home/dvateam128/webapps/team128_app/apache2/conf/httpd.conf'
[Sat Apr 18 22:15:47.263418 2020] [wsgi:error] [pid 3977:tid 139940455544576] [remote 127.0.0.1:41736] Not Found: /static/admin/css/fonts.css
[Sat Apr 18 22:16:06.230996 2020] [wsgi:error] [pid 3976:tid 139940293732096] [remote 127.0.0.1:44108] Not Found: /anguajif
[Sat Apr 18 22:21:43.748138 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00298: SIGHUP received.  Attempting to restart
[Sat Apr 18 22:21:43.949467 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00292: Apache/2.4.41 (Unix) mod_wsgi/4.7.1 Python/3.7 configured -- resuming normal operations
[Sat Apr 18 22:21:43.949489 2020] [core:notice] [pid 32761:tid 139940535924608] AH00094: Command line: '/home/dvateam128/webapps/team128_app/apache2/bin/httpd.worker -f /home/dvateam128/webapps/team128_app/apache2/conf/httpd.conf'
[Sat Apr 18 22:21:46.516464 2020] [wsgi:error] [pid 32323:tid 139940447151872] [remote 127.0.0.1:58396] Not Found: /anguajif
[Sat Apr 18 22:21:48.969445 2020] [wsgi:error] [pid 32323:tid 139940293764864] [remote 127.0.0.1:58766] Not Found: /static/admin/css/fonts.css
[Sat Apr 18 22:23:40.238210 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00298: SIGHUP received.  Attempting to restart
[Sat Apr 18 22:23:40.630616 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00292: Apache/2.4.41 (Unix) mod_wsgi/4.7.1 Python/3.7 configured -- resuming normal operations
[Sat Apr 18 22:23:40.630639 2020] [core:notice] [pid 32761:tid 139940535924608] AH00094: Command line: '/home/dvateam128/webapps/team128_app/apache2/bin/httpd.worker -f /home/dvateam128/webapps/team128_app/apache2/conf/httpd.conf'
[Sat Apr 18 22:23:41.155759 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:46044] mod_wsgi (pid=43032): Failed to exec Python script file '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:23:41.156065 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:46044] mod_wsgi (pid=43032): Exception occurred processing WSGI script '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:23:41.157675 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:46044] Traceback (most recent call last):
[Sat Apr 18 22:23:41.157755 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:46044]   File "/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py", line 8, in <module>
[Sat Apr 18 22:23:41.157762 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:46044]     application = get_wsgi_application()
[Sat Apr 18 22:23:41.157769 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:46044]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/wsgi.py", line 12, in get_wsgi_application
[Sat Apr 18 22:23:41.157774 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:46044]     django.setup(set_prefix=False)
[Sat Apr 18 22:23:41.157789 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:46044]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/__init__.py", line 24, in setup
[Sat Apr 18 22:23:41.157794 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:46044]     apps.populate(settings.INSTALLED_APPS)
[Sat Apr 18 22:23:41.157800 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:46044]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/apps/registry.py", line 91, in populate
[Sat Apr 18 22:23:41.157815 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:46044]     app_config = AppConfig.create(entry)
[Sat Apr 18 22:23:41.157822 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:46044]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/apps/config.py", line 116, in create
[Sat Apr 18 22:23:41.157826 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:46044]     mod = import_module(mod_path)
[Sat Apr 18 22:23:41.157832 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:46044]   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
[Sat Apr 18 22:23:41.157835 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:46044]     return _bootstrap._gcd_import(name[level:], package, level)
[Sat Apr 18 22:23:41.157841 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:46044]   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
[Sat Apr 18 22:23:41.157847 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:46044]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[Sat Apr 18 22:23:41.157852 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:46044]   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
[Sat Apr 18 22:23:41.157858 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:46044]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[Sat Apr 18 22:23:41.157864 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:46044]   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
[Sat Apr 18 22:23:41.157869 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:46044]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[Sat Apr 18 22:23:41.157875 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:46044]   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
[Sat Apr 18 22:23:41.157896 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:46044] ModuleNotFoundError: No module named 'stocks'
[Sat Apr 18 22:26:15.109499 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:38646] mod_wsgi (pid=43032): Failed to exec Python script file '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:26:15.109607 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:38646] mod_wsgi (pid=43032): Exception occurred processing WSGI script '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:26:15.110106 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:38646] Traceback (most recent call last):
[Sat Apr 18 22:26:15.110209 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:38646]   File "/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py", line 8, in <module>
[Sat Apr 18 22:26:15.110219 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:38646]     application = get_wsgi_application()
[Sat Apr 18 22:26:15.110234 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:38646]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/wsgi.py", line 12, in get_wsgi_application
[Sat Apr 18 22:26:15.110243 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:38646]     django.setup(set_prefix=False)
[Sat Apr 18 22:26:15.110274 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:38646]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/__init__.py", line 24, in setup
[Sat Apr 18 22:26:15.110284 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:38646]     apps.populate(settings.INSTALLED_APPS)
[Sat Apr 18 22:26:15.110298 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:38646]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/apps/registry.py", line 83, in populate
[Sat Apr 18 22:26:15.110306 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:38646]     raise RuntimeError("populate() isn't reentrant")
[Sat Apr 18 22:26:15.110341 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:38646] RuntimeError: populate() isn't reentrant
[Sat Apr 18 22:26:15.706669 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:38670] mod_wsgi (pid=43033): Failed to exec Python script file '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:26:15.706740 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:38670] mod_wsgi (pid=43033): Exception occurred processing WSGI script '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:26:15.707508 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:38670] Traceback (most recent call last):
[Sat Apr 18 22:26:15.707576 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:38670]   File "/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py", line 8, in <module>
[Sat Apr 18 22:26:15.707583 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:38670]     application = get_wsgi_application()
[Sat Apr 18 22:26:15.707589 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:38670]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/wsgi.py", line 12, in get_wsgi_application
[Sat Apr 18 22:26:15.707593 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:38670]     django.setup(set_prefix=False)
[Sat Apr 18 22:26:15.707598 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:38670]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/__init__.py", line 24, in setup
[Sat Apr 18 22:26:15.707601 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:38670]     apps.populate(settings.INSTALLED_APPS)
[Sat Apr 18 22:26:15.707606 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:38670]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/apps/registry.py", line 91, in populate
[Sat Apr 18 22:26:15.707610 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:38670]     app_config = AppConfig.create(entry)
[Sat Apr 18 22:26:15.707615 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:38670]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/apps/config.py", line 116, in create
[Sat Apr 18 22:26:15.707618 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:38670]     mod = import_module(mod_path)
[Sat Apr 18 22:26:15.707623 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:38670]   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
[Sat Apr 18 22:26:15.707626 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:38670]     return _bootstrap._gcd_import(name[level:], package, level)
[Sat Apr 18 22:26:15.707631 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:38670]   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
[Sat Apr 18 22:26:15.707636 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:38670]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[Sat Apr 18 22:26:15.707650 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:38670]   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
[Sat Apr 18 22:26:15.707656 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:38670]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[Sat Apr 18 22:26:15.707661 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:38670]   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
[Sat Apr 18 22:26:15.707666 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:38670]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[Sat Apr 18 22:26:15.707670 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:38670]   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
[Sat Apr 18 22:26:15.707689 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:38670] ModuleNotFoundError: No module named 'stocks'
[Sat Apr 18 22:26:33.282832 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:41092] mod_wsgi (pid=43032): Failed to exec Python script file '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:26:33.282899 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:41092] mod_wsgi (pid=43032): Exception occurred processing WSGI script '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:26:33.283030 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:41092] Traceback (most recent call last):
[Sat Apr 18 22:26:33.283068 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:41092]   File "/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py", line 8, in <module>
[Sat Apr 18 22:26:33.283073 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:41092]     application = get_wsgi_application()
[Sat Apr 18 22:26:33.283080 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:41092]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/wsgi.py", line 12, in get_wsgi_application
[Sat Apr 18 22:26:33.283084 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:41092]     django.setup(set_prefix=False)
[Sat Apr 18 22:26:33.283089 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:41092]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/__init__.py", line 24, in setup
[Sat Apr 18 22:26:33.283093 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:41092]     apps.populate(settings.INSTALLED_APPS)
[Sat Apr 18 22:26:33.283099 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:41092]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/apps/registry.py", line 83, in populate
[Sat Apr 18 22:26:33.283103 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:41092]     raise RuntimeError("populate() isn't reentrant")
[Sat Apr 18 22:26:33.283119 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:41092] RuntimeError: populate() isn't reentrant
[Sat Apr 18 22:26:33.369697 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:41104] mod_wsgi (pid=43033): Failed to exec Python script file '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:26:33.369785 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:41104] mod_wsgi (pid=43033): Exception occurred processing WSGI script '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:26:33.369987 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:41104] Traceback (most recent call last):
[Sat Apr 18 22:26:33.370055 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:41104]   File "/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py", line 8, in <module>
[Sat Apr 18 22:26:33.370077 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:41104]     application = get_wsgi_application()
[Sat Apr 18 22:26:33.370088 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:41104]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/wsgi.py", line 12, in get_wsgi_application
[Sat Apr 18 22:26:33.370095 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:41104]     django.setup(set_prefix=False)
[Sat Apr 18 22:26:33.370104 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:41104]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/__init__.py", line 24, in setup
[Sat Apr 18 22:26:33.370110 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:41104]     apps.populate(settings.INSTALLED_APPS)
[Sat Apr 18 22:26:33.370117 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:41104]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/apps/registry.py", line 83, in populate
[Sat Apr 18 22:26:33.370123 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:41104]     raise RuntimeError("populate() isn't reentrant")
[Sat Apr 18 22:26:33.370148 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:41104] RuntimeError: populate() isn't reentrant
[Sat Apr 18 22:26:34.611124 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:41268] mod_wsgi (pid=43032): Failed to exec Python script file '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:26:34.611237 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:41268] mod_wsgi (pid=43032): Exception occurred processing WSGI script '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:26:34.611498 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:41268] Traceback (most recent call last):
[Sat Apr 18 22:26:34.611582 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:41268]   File "/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py", line 8, in <module>
[Sat Apr 18 22:26:34.611595 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:41268]     application = get_wsgi_application()
[Sat Apr 18 22:26:34.611611 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:41268]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/wsgi.py", line 12, in get_wsgi_application
[Sat Apr 18 22:26:34.611620 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:41268]     django.setup(set_prefix=False)
[Sat Apr 18 22:26:34.611633 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:41268]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/__init__.py", line 24, in setup
[Sat Apr 18 22:26:34.611641 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:41268]     apps.populate(settings.INSTALLED_APPS)
[Sat Apr 18 22:26:34.611653 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:41268]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/apps/registry.py", line 83, in populate
[Sat Apr 18 22:26:34.611660 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:41268]     raise RuntimeError("populate() isn't reentrant")
[Sat Apr 18 22:26:34.611697 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:41268] RuntimeError: populate() isn't reentrant
[Sat Apr 18 22:26:34.798104 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:41304] mod_wsgi (pid=43033): Failed to exec Python script file '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:26:34.798178 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:41304] mod_wsgi (pid=43033): Exception occurred processing WSGI script '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:26:34.798356 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:41304] Traceback (most recent call last):
[Sat Apr 18 22:26:34.798411 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:41304]   File "/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py", line 8, in <module>
[Sat Apr 18 22:26:34.798418 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:41304]     application = get_wsgi_application()
[Sat Apr 18 22:26:34.798428 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:41304]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/wsgi.py", line 12, in get_wsgi_application
[Sat Apr 18 22:26:34.798434 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:41304]     django.setup(set_prefix=False)
[Sat Apr 18 22:26:34.798441 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:41304]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/__init__.py", line 24, in setup
[Sat Apr 18 22:26:34.798447 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:41304]     apps.populate(settings.INSTALLED_APPS)
[Sat Apr 18 22:26:34.798454 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:41304]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/apps/registry.py", line 83, in populate
[Sat Apr 18 22:26:34.798459 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:41304]     raise RuntimeError("populate() isn't reentrant")
[Sat Apr 18 22:26:34.798481 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:41304] RuntimeError: populate() isn't reentrant
[Sat Apr 18 22:26:39.851167 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:42012] mod_wsgi (pid=43032): Failed to exec Python script file '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:26:39.851240 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:42012] mod_wsgi (pid=43032): Exception occurred processing WSGI script '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:26:39.851381 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:42012] Traceback (most recent call last):
[Sat Apr 18 22:26:39.851425 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:42012]   File "/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py", line 8, in <module>
[Sat Apr 18 22:26:39.851431 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:42012]     application = get_wsgi_application()
[Sat Apr 18 22:26:39.851439 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:42012]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/wsgi.py", line 12, in get_wsgi_application
[Sat Apr 18 22:26:39.851444 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:42012]     django.setup(set_prefix=False)
[Sat Apr 18 22:26:39.851450 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:42012]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/__init__.py", line 24, in setup
[Sat Apr 18 22:26:39.851455 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:42012]     apps.populate(settings.INSTALLED_APPS)
[Sat Apr 18 22:26:39.851461 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:42012]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/apps/registry.py", line 83, in populate
[Sat Apr 18 22:26:39.851466 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:42012]     raise RuntimeError("populate() isn't reentrant")
[Sat Apr 18 22:26:39.851485 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:42012] RuntimeError: populate() isn't reentrant
[Sat Apr 18 22:26:50.969706 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:43332] mod_wsgi (pid=43033): Failed to exec Python script file '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:26:50.969783 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:43332] mod_wsgi (pid=43033): Exception occurred processing WSGI script '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:26:50.970166 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:43332] Traceback (most recent call last):
[Sat Apr 18 22:26:50.970218 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:43332]   File "/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py", line 8, in <module>
[Sat Apr 18 22:26:50.970223 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:43332]     application = get_wsgi_application()
[Sat Apr 18 22:26:50.970230 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:43332]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/wsgi.py", line 12, in get_wsgi_application
[Sat Apr 18 22:26:50.970235 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:43332]     django.setup(set_prefix=False)
[Sat Apr 18 22:26:50.970294 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:43332]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/__init__.py", line 24, in setup
[Sat Apr 18 22:26:50.970312 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:43332]     apps.populate(settings.INSTALLED_APPS)
[Sat Apr 18 22:26:50.970319 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:43332]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/apps/registry.py", line 83, in populate
[Sat Apr 18 22:26:50.970324 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:43332]     raise RuntimeError("populate() isn't reentrant")
[Sat Apr 18 22:26:50.970359 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:43332] RuntimeError: populate() isn't reentrant
[Sat Apr 18 22:26:53.187578 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:43632] mod_wsgi (pid=43032): Failed to exec Python script file '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:26:53.187637 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:43632] mod_wsgi (pid=43032): Exception occurred processing WSGI script '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:26:53.187771 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:43632] Traceback (most recent call last):
[Sat Apr 18 22:26:53.188072 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:43632]   File "/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py", line 8, in <module>
[Sat Apr 18 22:26:53.188083 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:43632]     application = get_wsgi_application()
[Sat Apr 18 22:26:53.188091 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:43632]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/wsgi.py", line 12, in get_wsgi_application
[Sat Apr 18 22:26:53.188095 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:43632]     django.setup(set_prefix=False)
[Sat Apr 18 22:26:53.188101 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:43632]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/__init__.py", line 24, in setup
[Sat Apr 18 22:26:53.188104 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:43632]     apps.populate(settings.INSTALLED_APPS)
[Sat Apr 18 22:26:53.188110 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:43632]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/apps/registry.py", line 83, in populate
[Sat Apr 18 22:26:53.188125 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:43632]     raise RuntimeError("populate() isn't reentrant")
[Sat Apr 18 22:26:53.188146 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:43632] RuntimeError: populate() isn't reentrant
[Sat Apr 18 22:26:53.320489 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:43656] mod_wsgi (pid=43032): Failed to exec Python script file '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:26:53.320556 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:43656] mod_wsgi (pid=43032): Exception occurred processing WSGI script '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:26:53.320728 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:43656] Traceback (most recent call last):
[Sat Apr 18 22:26:53.320783 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:43656]   File "/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py", line 8, in <module>
[Sat Apr 18 22:26:53.320791 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:43656]     application = get_wsgi_application()
[Sat Apr 18 22:26:53.320800 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:43656]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/wsgi.py", line 12, in get_wsgi_application
[Sat Apr 18 22:26:53.321048 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:43656]     django.setup(set_prefix=False)
[Sat Apr 18 22:26:53.321063 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:43656]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/__init__.py", line 24, in setup
[Sat Apr 18 22:26:53.321070 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:43656]     apps.populate(settings.INSTALLED_APPS)
[Sat Apr 18 22:26:53.321078 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:43656]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/apps/registry.py", line 83, in populate
[Sat Apr 18 22:26:53.321084 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:43656]     raise RuntimeError("populate() isn't reentrant")
[Sat Apr 18 22:26:53.321109 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:43656] RuntimeError: populate() isn't reentrant
[Sat Apr 18 22:27:28.001285 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:48296] mod_wsgi (pid=43033): Failed to exec Python script file '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:27:28.001648 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:48296] mod_wsgi (pid=43033): Exception occurred processing WSGI script '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:27:28.001903 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:48296] Traceback (most recent call last):
[Sat Apr 18 22:27:28.001987 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:48296]   File "/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py", line 8, in <module>
[Sat Apr 18 22:27:28.001998 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:48296]     application = get_wsgi_application()
[Sat Apr 18 22:27:28.002012 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:48296]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/wsgi.py", line 12, in get_wsgi_application
[Sat Apr 18 22:27:28.002021 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:48296]     django.setup(set_prefix=False)
[Sat Apr 18 22:27:28.002034 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:48296]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/__init__.py", line 24, in setup
[Sat Apr 18 22:27:28.002065 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:48296]     apps.populate(settings.INSTALLED_APPS)
[Sat Apr 18 22:27:28.002081 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:48296]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/apps/registry.py", line 83, in populate
[Sat Apr 18 22:27:28.002089 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:48296]     raise RuntimeError("populate() isn't reentrant")
[Sat Apr 18 22:27:28.002123 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:48296] RuntimeError: populate() isn't reentrant
[Sat Apr 18 22:27:28.862464 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:48398] mod_wsgi (pid=43032): Failed to exec Python script file '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:27:28.862550 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:48398] mod_wsgi (pid=43032): Exception occurred processing WSGI script '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:27:28.862727 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:48398] Traceback (most recent call last):
[Sat Apr 18 22:27:28.862784 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:48398]   File "/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py", line 8, in <module>
[Sat Apr 18 22:27:28.862791 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:48398]     application = get_wsgi_application()
[Sat Apr 18 22:27:28.862810 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:48398]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/wsgi.py", line 12, in get_wsgi_application
[Sat Apr 18 22:27:28.862822 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:48398]     django.setup(set_prefix=False)
[Sat Apr 18 22:27:28.862832 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:48398]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/__init__.py", line 24, in setup
[Sat Apr 18 22:27:28.862838 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:48398]     apps.populate(settings.INSTALLED_APPS)
[Sat Apr 18 22:27:28.862846 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:48398]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/apps/registry.py", line 83, in populate
[Sat Apr 18 22:27:28.862852 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:48398]     raise RuntimeError("populate() isn't reentrant")
[Sat Apr 18 22:27:28.862878 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:48398] RuntimeError: populate() isn't reentrant
[Sat Apr 18 22:27:30.171728 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:48558] mod_wsgi (pid=43033): Failed to exec Python script file '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:27:30.171813 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:48558] mod_wsgi (pid=43033): Exception occurred processing WSGI script '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:27:30.172220 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:48558] Traceback (most recent call last):
[Sat Apr 18 22:27:30.172272 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:48558]   File "/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py", line 8, in <module>
[Sat Apr 18 22:27:30.172279 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:48558]     application = get_wsgi_application()
[Sat Apr 18 22:27:30.172288 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:48558]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/wsgi.py", line 12, in get_wsgi_application
[Sat Apr 18 22:27:30.172305 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:48558]     django.setup(set_prefix=False)
[Sat Apr 18 22:27:30.172313 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:48558]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/__init__.py", line 24, in setup
[Sat Apr 18 22:27:30.172319 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:48558]     apps.populate(settings.INSTALLED_APPS)
[Sat Apr 18 22:27:30.172326 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:48558]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/apps/registry.py", line 83, in populate
[Sat Apr 18 22:27:30.172331 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:48558]     raise RuntimeError("populate() isn't reentrant")
[Sat Apr 18 22:27:30.172353 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:48558] RuntimeError: populate() isn't reentrant
[Sat Apr 18 22:28:20.790405 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:55214] mod_wsgi (pid=43032): Failed to exec Python script file '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:28:20.790491 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:55214] mod_wsgi (pid=43032): Exception occurred processing WSGI script '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:28:20.790658 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:55214] Traceback (most recent call last):
[Sat Apr 18 22:28:20.790710 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:55214]   File "/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py", line 8, in <module>
[Sat Apr 18 22:28:20.790717 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:55214]     application = get_wsgi_application()
[Sat Apr 18 22:28:20.790727 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:55214]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/wsgi.py", line 12, in get_wsgi_application
[Sat Apr 18 22:28:20.790733 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:55214]     django.setup(set_prefix=False)
[Sat Apr 18 22:28:20.790741 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:55214]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/__init__.py", line 24, in setup
[Sat Apr 18 22:28:20.790746 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:55214]     apps.populate(settings.INSTALLED_APPS)
[Sat Apr 18 22:28:20.790754 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:55214]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/apps/registry.py", line 83, in populate
[Sat Apr 18 22:28:20.790759 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:55214]     raise RuntimeError("populate() isn't reentrant")
[Sat Apr 18 22:28:20.790782 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:55214] RuntimeError: populate() isn't reentrant
[Sat Apr 18 22:28:44.316571 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:58006] mod_wsgi (pid=43033): Failed to exec Python script file '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:28:44.316654 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:58006] mod_wsgi (pid=43033): Exception occurred processing WSGI script '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:28:44.316814 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:58006] Traceback (most recent call last):
[Sat Apr 18 22:28:44.317131 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:58006]   File "/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py", line 8, in <module>
[Sat Apr 18 22:28:44.317161 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:58006]     application = get_wsgi_application()
[Sat Apr 18 22:28:44.317170 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:58006]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/wsgi.py", line 12, in get_wsgi_application
[Sat Apr 18 22:28:44.317175 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:58006]     django.setup(set_prefix=False)
[Sat Apr 18 22:28:44.317181 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:58006]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/__init__.py", line 24, in setup
[Sat Apr 18 22:28:44.317185 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:58006]     apps.populate(settings.INSTALLED_APPS)
[Sat Apr 18 22:28:44.317191 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:58006]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/apps/registry.py", line 83, in populate
[Sat Apr 18 22:28:44.317195 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:58006]     raise RuntimeError("populate() isn't reentrant")
[Sat Apr 18 22:28:44.317216 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:58006] RuntimeError: populate() isn't reentrant
[Sat Apr 18 22:28:44.451287 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:58040] mod_wsgi (pid=43033): Failed to exec Python script file '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:28:44.451351 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:58040] mod_wsgi (pid=43033): Exception occurred processing WSGI script '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:28:44.451509 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:58040] Traceback (most recent call last):
[Sat Apr 18 22:28:44.451563 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:58040]   File "/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py", line 8, in <module>
[Sat Apr 18 22:28:44.451570 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:58040]     application = get_wsgi_application()
[Sat Apr 18 22:28:44.451578 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:58040]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/wsgi.py", line 12, in get_wsgi_application
[Sat Apr 18 22:28:44.451585 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:58040]     django.setup(set_prefix=False)
[Sat Apr 18 22:28:44.451592 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:58040]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/__init__.py", line 24, in setup
[Sat Apr 18 22:28:44.451598 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:58040]     apps.populate(settings.INSTALLED_APPS)
[Sat Apr 18 22:28:44.451605 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:58040]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/apps/registry.py", line 83, in populate
[Sat Apr 18 22:28:44.451610 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:58040]     raise RuntimeError("populate() isn't reentrant")
[Sat Apr 18 22:28:44.451631 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:58040] RuntimeError: populate() isn't reentrant
[Sat Apr 18 22:29:04.029104 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:60376] mod_wsgi (pid=43033): Failed to exec Python script file '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:29:04.029169 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:60376] mod_wsgi (pid=43033): Exception occurred processing WSGI script '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:29:04.029322 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:60376] Traceback (most recent call last):
[Sat Apr 18 22:29:04.029372 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:60376]   File "/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py", line 8, in <module>
[Sat Apr 18 22:29:04.029378 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:60376]     application = get_wsgi_application()
[Sat Apr 18 22:29:04.029387 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:60376]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/wsgi.py", line 12, in get_wsgi_application
[Sat Apr 18 22:29:04.029391 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:60376]     django.setup(set_prefix=False)
[Sat Apr 18 22:29:04.029398 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:60376]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/__init__.py", line 24, in setup
[Sat Apr 18 22:29:04.029402 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:60376]     apps.populate(settings.INSTALLED_APPS)
[Sat Apr 18 22:29:04.029409 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:60376]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/apps/registry.py", line 83, in populate
[Sat Apr 18 22:29:04.029413 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:60376]     raise RuntimeError("populate() isn't reentrant")
[Sat Apr 18 22:29:04.029433 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:60376] RuntimeError: populate() isn't reentrant
[Sat Apr 18 22:29:04.130297 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:60388] mod_wsgi (pid=43032): Failed to exec Python script file '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:29:04.130394 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:60388] mod_wsgi (pid=43032): Exception occurred processing WSGI script '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:29:04.130594 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:60388] Traceback (most recent call last):
[Sat Apr 18 22:29:04.130657 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:60388]   File "/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py", line 8, in <module>
[Sat Apr 18 22:29:04.130665 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:60388]     application = get_wsgi_application()
[Sat Apr 18 22:29:04.130681 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:60388]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/wsgi.py", line 12, in get_wsgi_application
[Sat Apr 18 22:29:04.130688 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:60388]     django.setup(set_prefix=False)
[Sat Apr 18 22:29:04.130696 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:60388]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/__init__.py", line 24, in setup
[Sat Apr 18 22:29:04.130702 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:60388]     apps.populate(settings.INSTALLED_APPS)
[Sat Apr 18 22:29:04.130711 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:60388]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/apps/registry.py", line 83, in populate
[Sat Apr 18 22:29:04.130717 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:60388]     raise RuntimeError("populate() isn't reentrant")
[Sat Apr 18 22:29:04.130746 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:60388] RuntimeError: populate() isn't reentrant
[Sat Apr 18 22:29:04.512137 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:60472] mod_wsgi (pid=43033): Failed to exec Python script file '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:29:04.512238 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:60472] mod_wsgi (pid=43033): Exception occurred processing WSGI script '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:29:04.512457 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:60472] Traceback (most recent call last):
[Sat Apr 18 22:29:04.512527 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:60472]   File "/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py", line 8, in <module>
[Sat Apr 18 22:29:04.512537 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:60472]     application = get_wsgi_application()
[Sat Apr 18 22:29:04.512550 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:60472]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/wsgi.py", line 12, in get_wsgi_application
[Sat Apr 18 22:29:04.512557 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:60472]     django.setup(set_prefix=False)
[Sat Apr 18 22:29:04.512568 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:60472]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/__init__.py", line 24, in setup
[Sat Apr 18 22:29:04.512575 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:60472]     apps.populate(settings.INSTALLED_APPS)
[Sat Apr 18 22:29:04.512585 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:60472]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/apps/registry.py", line 83, in populate
[Sat Apr 18 22:29:04.512592 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:60472]     raise RuntimeError("populate() isn't reentrant")
[Sat Apr 18 22:29:04.512622 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:60472] RuntimeError: populate() isn't reentrant
[Sat Apr 18 22:29:42.770882 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:36686] mod_wsgi (pid=43032): Failed to exec Python script file '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:29:42.770983 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:36686] mod_wsgi (pid=43032): Exception occurred processing WSGI script '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:29:42.771180 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:36686] Traceback (most recent call last):
[Sat Apr 18 22:29:42.771239 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:36686]   File "/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py", line 8, in <module>
[Sat Apr 18 22:29:42.771247 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:36686]     application = get_wsgi_application()
[Sat Apr 18 22:29:42.771258 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:36686]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/wsgi.py", line 12, in get_wsgi_application
[Sat Apr 18 22:29:42.771264 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:36686]     django.setup(set_prefix=False)
[Sat Apr 18 22:29:42.771273 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:36686]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/__init__.py", line 24, in setup
[Sat Apr 18 22:29:42.771279 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:36686]     apps.populate(settings.INSTALLED_APPS)
[Sat Apr 18 22:29:42.771287 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:36686]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/apps/registry.py", line 83, in populate
[Sat Apr 18 22:29:42.771301 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:36686]     raise RuntimeError("populate() isn't reentrant")
[Sat Apr 18 22:29:42.771329 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:36686] RuntimeError: populate() isn't reentrant
[Sat Apr 18 22:29:42.899359 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:36704] mod_wsgi (pid=43032): Failed to exec Python script file '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:29:42.899440 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:36704] mod_wsgi (pid=43032): Exception occurred processing WSGI script '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:29:42.899606 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:36704] Traceback (most recent call last):
[Sat Apr 18 22:29:42.899676 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:36704]   File "/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py", line 8, in <module>
[Sat Apr 18 22:29:42.899686 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:36704]     application = get_wsgi_application()
[Sat Apr 18 22:29:42.899698 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:36704]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/wsgi.py", line 12, in get_wsgi_application
[Sat Apr 18 22:29:42.899707 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:36704]     django.setup(set_prefix=False)
[Sat Apr 18 22:29:42.899719 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:36704]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/__init__.py", line 24, in setup
[Sat Apr 18 22:29:42.899726 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:36704]     apps.populate(settings.INSTALLED_APPS)
[Sat Apr 18 22:29:42.899734 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:36704]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/apps/registry.py", line 83, in populate
[Sat Apr 18 22:29:42.899739 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:36704]     raise RuntimeError("populate() isn't reentrant")
[Sat Apr 18 22:29:42.899763 2020] [wsgi:error] [pid 43032:tid 139940421973760] [remote 127.0.0.1:36704] RuntimeError: populate() isn't reentrant
[Sat Apr 18 22:29:43.920095 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:36854] mod_wsgi (pid=43033): Failed to exec Python script file '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:29:43.920168 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:36854] mod_wsgi (pid=43033): Exception occurred processing WSGI script '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:29:43.920316 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:36854] Traceback (most recent call last):
[Sat Apr 18 22:29:43.920364 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:36854]   File "/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py", line 8, in <module>
[Sat Apr 18 22:29:43.920370 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:36854]     application = get_wsgi_application()
[Sat Apr 18 22:29:43.920379 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:36854]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/wsgi.py", line 12, in get_wsgi_application
[Sat Apr 18 22:29:43.920384 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:36854]     django.setup(set_prefix=False)
[Sat Apr 18 22:29:43.920390 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:36854]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/__init__.py", line 24, in setup
[Sat Apr 18 22:29:43.920404 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:36854]     apps.populate(settings.INSTALLED_APPS)
[Sat Apr 18 22:29:43.920412 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:36854]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/apps/registry.py", line 83, in populate
[Sat Apr 18 22:29:43.920416 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:36854]     raise RuntimeError("populate() isn't reentrant")
[Sat Apr 18 22:29:43.920437 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:36854] RuntimeError: populate() isn't reentrant
[Sat Apr 18 22:29:44.021714 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:36884] mod_wsgi (pid=43033): Failed to exec Python script file '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:29:44.021835 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:36884] mod_wsgi (pid=43033): Exception occurred processing WSGI script '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:29:44.022069 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:36884] Traceback (most recent call last):
[Sat Apr 18 22:29:44.022142 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:36884]   File "/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py", line 8, in <module>
[Sat Apr 18 22:29:44.022151 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:36884]     application = get_wsgi_application()
[Sat Apr 18 22:29:44.022163 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:36884]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/wsgi.py", line 12, in get_wsgi_application
[Sat Apr 18 22:29:44.022171 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:36884]     django.setup(set_prefix=False)
[Sat Apr 18 22:29:44.022182 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:36884]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/__init__.py", line 24, in setup
[Sat Apr 18 22:29:44.022189 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:36884]     apps.populate(settings.INSTALLED_APPS)
[Sat Apr 18 22:29:44.022199 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:36884]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/apps/registry.py", line 83, in populate
[Sat Apr 18 22:29:44.022206 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:36884]     raise RuntimeError("populate() isn't reentrant")
[Sat Apr 18 22:29:44.022237 2020] [wsgi:error] [pid 43033:tid 139940363224832] [remote 127.0.0.1:36884] RuntimeError: populate() isn't reentrant
[Sat Apr 18 22:29:45.252999 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:37090] mod_wsgi (pid=43033): Failed to exec Python script file '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:29:45.253063 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:37090] mod_wsgi (pid=43033): Exception occurred processing WSGI script '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:29:45.253219 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:37090] Traceback (most recent call last):
[Sat Apr 18 22:29:45.253270 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:37090]   File "/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py", line 8, in <module>
[Sat Apr 18 22:29:45.253278 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:37090]     application = get_wsgi_application()
[Sat Apr 18 22:29:45.253287 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:37090]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/wsgi.py", line 12, in get_wsgi_application
[Sat Apr 18 22:29:45.253299 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:37090]     django.setup(set_prefix=False)
[Sat Apr 18 22:29:45.253307 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:37090]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/__init__.py", line 24, in setup
[Sat Apr 18 22:29:45.253312 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:37090]     apps.populate(settings.INSTALLED_APPS)
[Sat Apr 18 22:29:45.253320 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:37090]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/apps/registry.py", line 83, in populate
[Sat Apr 18 22:29:45.253325 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:37090]     raise RuntimeError("populate() isn't reentrant")
[Sat Apr 18 22:29:45.253346 2020] [wsgi:error] [pid 43033:tid 139940455544576] [remote 127.0.0.1:37090] RuntimeError: populate() isn't reentrant
[Sat Apr 18 22:31:00.519355 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:46712] mod_wsgi (pid=43032): Failed to exec Python script file '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:31:00.519428 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:46712] mod_wsgi (pid=43032): Exception occurred processing WSGI script '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:31:00.519599 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:46712] Traceback (most recent call last):
[Sat Apr 18 22:31:00.519653 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:46712]   File "/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py", line 8, in <module>
[Sat Apr 18 22:31:00.519661 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:46712]     application = get_wsgi_application()
[Sat Apr 18 22:31:00.519671 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:46712]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/wsgi.py", line 12, in get_wsgi_application
[Sat Apr 18 22:31:00.519677 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:46712]     django.setup(set_prefix=False)
[Sat Apr 18 22:31:00.519685 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:46712]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/__init__.py", line 24, in setup
[Sat Apr 18 22:31:00.519690 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:46712]     apps.populate(settings.INSTALLED_APPS)
[Sat Apr 18 22:31:00.519698 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:46712]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/apps/registry.py", line 83, in populate
[Sat Apr 18 22:31:00.519704 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:46712]     raise RuntimeError("populate() isn't reentrant")
[Sat Apr 18 22:31:00.519727 2020] [wsgi:error] [pid 43032:tid 139940455544576] [remote 127.0.0.1:46712] RuntimeError: populate() isn't reentrant
[Sat Apr 18 22:31:46.527771 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00298: SIGHUP received.  Attempting to restart
[Sat Apr 18 22:31:46.730227 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00292: Apache/2.4.41 (Unix) mod_wsgi/4.7.1 Python/3.7 configured -- resuming normal operations
[Sat Apr 18 22:31:46.730264 2020] [core:notice] [pid 32761:tid 139940535924608] AH00094: Command line: '/home/dvateam128/webapps/team128_app/apache2/bin/httpd.worker -f /home/dvateam128/webapps/team128_app/apache2/conf/httpd.conf'
[Sat Apr 18 22:32:05.100945 2020] [wsgi:error] [pid 31950:tid 139940455544576] [remote 127.0.0.1:54936] Not Found: /static/admin/css/fonts.css
[Sat Apr 18 22:32:08.918922 2020] [wsgi:error] [pid 31951:tid 139940455544576] [remote 127.0.0.1:55566] Not Found: /static/admin/css/fonts.css
[Sat Apr 18 22:32:08.957236 2020] [wsgi:error] [pid 31950:tid 139940363224832] [remote 127.0.0.1:55568] Not Found: /favicon.ico
[Sat Apr 18 22:32:10.032173 2020] [wsgi:error] [pid 31950:tid 139940455544576] [remote 127.0.0.1:55712] Not Found: /static/admin/css/fonts.css
[Sat Apr 18 22:32:10.069594 2020] [wsgi:error] [pid 31951:tid 139940455544576] [remote 127.0.0.1:55724] Not Found: /favicon.ico
[Sat Apr 18 22:32:10.783057 2020] [wsgi:error] [pid 31951:tid 139940293764864] [remote 127.0.0.1:55806] Not Found: /static/admin/css/fonts.css
[Sat Apr 18 22:33:10.827119 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00298: SIGHUP received.  Attempting to restart
[Sat Apr 18 22:33:11.029078 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00292: Apache/2.4.41 (Unix) mod_wsgi/4.7.1 Python/3.7 configured -- resuming normal operations
[Sat Apr 18 22:33:11.029120 2020] [core:notice] [pid 32761:tid 139940535924608] AH00094: Command line: '/home/dvateam128/webapps/team128_app/apache2/bin/httpd.worker -f /home/dvateam128/webapps/team128_app/apache2/conf/httpd.conf'
[Sat Apr 18 22:33:11.820410 2020] [wsgi:error] [pid 38695:tid 139940369266432] [remote 127.0.0.1:36036] Not Found: /static/admin/css/fonts.css
[Sat Apr 18 22:33:16.927666 2020] [wsgi:error] [pid 38696:tid 139940455544576] [remote 127.0.0.1:36570] Not Found: /hello
[Sat Apr 18 22:33:17.078779 2020] [wsgi:error] [pid 38695:tid 139940455544576] [remote 127.0.0.1:36692] Not Found: /favicon.ico
[Sat Apr 18 22:33:20.862186 2020] [wsgi:error] [pid 38695:tid 139940369266432] [remote 127.0.0.1:37212] Not Found: /static/admin/css/fonts.css
[Sat Apr 18 22:33:20.898163 2020] [wsgi:error] [pid 38696:tid 139940455544576] [remote 127.0.0.1:37216] Not Found: /favicon.ico
[Sat Apr 18 22:34:02.829365 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00298: SIGHUP received.  Attempting to restart
[Sat Apr 18 22:34:03.027470 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00292: Apache/2.4.41 (Unix) mod_wsgi/4.7.1 Python/3.7 configured -- resuming normal operations
[Sat Apr 18 22:34:03.027496 2020] [core:notice] [pid 32761:tid 139940535924608] AH00094: Command line: '/home/dvateam128/webapps/team128_app/apache2/bin/httpd.worker -f /home/dvateam128/webapps/team128_app/apache2/conf/httpd.conf'
[Sat Apr 18 22:34:05.540633 2020] [wsgi:error] [pid 42130:tid 139940455544576] [remote 127.0.0.1:43118] mod_wsgi (pid=42130): Failed to exec Python script file '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:34:05.540727 2020] [wsgi:error] [pid 42130:tid 139940455544576] [remote 127.0.0.1:43118] mod_wsgi (pid=42130): Exception occurred processing WSGI script '/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py'.
[Sat Apr 18 22:34:05.541531 2020] [wsgi:error] [pid 42130:tid 139940455544576] [remote 127.0.0.1:43118] Traceback (most recent call last):
[Sat Apr 18 22:34:05.541584 2020] [wsgi:error] [pid 42130:tid 139940455544576] [remote 127.0.0.1:43118]   File "/home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py", line 8, in <module>
[Sat Apr 18 22:34:05.541590 2020] [wsgi:error] [pid 42130:tid 139940455544576] [remote 127.0.0.1:43118]     application = get_wsgi_application()
[Sat Apr 18 22:34:05.541597 2020] [wsgi:error] [pid 42130:tid 139940455544576] [remote 127.0.0.1:43118]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/wsgi.py", line 12, in get_wsgi_application
[Sat Apr 18 22:34:05.541601 2020] [wsgi:error] [pid 42130:tid 139940455544576] [remote 127.0.0.1:43118]     django.setup(set_prefix=False)
[Sat Apr 18 22:34:05.541606 2020] [wsgi:error] [pid 42130:tid 139940455544576] [remote 127.0.0.1:43118]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/__init__.py", line 24, in setup
[Sat Apr 18 22:34:05.541610 2020] [wsgi:error] [pid 42130:tid 139940455544576] [remote 127.0.0.1:43118]     apps.populate(settings.INSTALLED_APPS)
[Sat Apr 18 22:34:05.541629 2020] [wsgi:error] [pid 42130:tid 139940455544576] [remote 127.0.0.1:43118]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/apps/registry.py", line 91, in populate
[Sat Apr 18 22:34:05.541633 2020] [wsgi:error] [pid 42130:tid 139940455544576] [remote 127.0.0.1:43118]     app_config = AppConfig.create(entry)
[Sat Apr 18 22:34:05.541638 2020] [wsgi:error] [pid 42130:tid 139940455544576] [remote 127.0.0.1:43118]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/apps/config.py", line 90, in create
[Sat Apr 18 22:34:05.541641 2020] [wsgi:error] [pid 42130:tid 139940455544576] [remote 127.0.0.1:43118]     module = import_module(entry)
[Sat Apr 18 22:34:05.541647 2020] [wsgi:error] [pid 42130:tid 139940455544576] [remote 127.0.0.1:43118]   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
[Sat Apr 18 22:34:05.541650 2020] [wsgi:error] [pid 42130:tid 139940455544576] [remote 127.0.0.1:43118]     return _bootstrap._gcd_import(name[level:], package, level)
[Sat Apr 18 22:34:05.541655 2020] [wsgi:error] [pid 42130:tid 139940455544576] [remote 127.0.0.1:43118]   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
[Sat Apr 18 22:34:05.541660 2020] [wsgi:error] [pid 42130:tid 139940455544576] [remote 127.0.0.1:43118]   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
[Sat Apr 18 22:34:05.541665 2020] [wsgi:error] [pid 42130:tid 139940455544576] [remote 127.0.0.1:43118]   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
[Sat Apr 18 22:34:05.541684 2020] [wsgi:error] [pid 42130:tid 139940455544576] [remote 127.0.0.1:43118] ModuleNotFoundError: No module named 'rest_framework'
[Sat Apr 18 22:34:52.697530 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00298: SIGHUP received.  Attempting to restart
[Sat Apr 18 22:34:52.893641 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00292: Apache/2.4.41 (Unix) mod_wsgi/4.7.1 Python/3.7 configured -- resuming normal operations
[Sat Apr 18 22:34:52.893667 2020] [core:notice] [pid 32761:tid 139940535924608] AH00094: Command line: '/home/dvateam128/webapps/team128_app/apache2/bin/httpd.worker -f /home/dvateam128/webapps/team128_app/apache2/conf/httpd.conf'
[Sat Apr 18 22:34:58.393400 2020] [wsgi:error] [pid 46245:tid 139940293764864] [remote 127.0.0.1:50552] Not Found: /static/admin/css/fonts.css
[Sat Apr 18 22:34:58.998503 2020] [wsgi:error] [pid 46248:tid 139940455544576] [remote 127.0.0.1:50556] Not Found: /favicon.ico
[Sat Apr 18 22:40:40.741897 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00298: SIGHUP received.  Attempting to restart
[Sat Apr 18 22:40:40.942493 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00292: Apache/2.4.41 (Unix) mod_wsgi/4.7.1 Python/3.7 configured -- resuming normal operations
[Sat Apr 18 22:40:40.942522 2020] [core:notice] [pid 32761:tid 139940535924608] AH00094: Command line: '/home/dvateam128/webapps/team128_app/apache2/bin/httpd.worker -f /home/dvateam128/webapps/team128_app/apache2/conf/httpd.conf'
[Sat Apr 18 22:40:43.293256 2020] [wsgi:error] [pid 26807:tid 139940455544576] [remote 127.0.0.1:42620] Not Found: /
[Sat Apr 18 22:41:35.289702 2020] [wsgi:error] [pid 26806:tid 139940363224832] [remote 127.0.0.1:49336] Not Found: /favicon.ico
[Sat Apr 18 22:41:45.122917 2020] [wsgi:error] [pid 26807:tid 139940293764864] [remote 127.0.0.1:50694] Not Found: /robots.txt
[Sat Apr 18 22:41:51.252555 2020] [wsgi:error] [pid 26807:tid 139940455544576] [remote 127.0.0.1:51576] Not Found: /favicon.ico
[Sat Apr 18 22:46:18.626330 2020] [wsgi:error] [pid 26807:tid 139940455544576] [remote 127.0.0.1:57564] Not Found: /favicon.ico
[Sat Apr 18 23:01:10.119447 2020] [wsgi:error] [pid 26806:tid 139940363224832] [remote 127.0.0.1:36714] Not Found: /api/{symbol}
[Sun Apr 19 00:50:55.880201 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00298: SIGHUP received.  Attempting to restart
[Sun Apr 19 00:50:56.077927 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00292: Apache/2.4.41 (Unix) mod_wsgi/4.7.1 Python/3.7 configured -- resuming normal operations
[Sun Apr 19 00:50:56.077976 2020] [core:notice] [pid 32761:tid 139940535924608] AH00094: Command line: '/home/dvateam128/webapps/team128_app/apache2/bin/httpd.worker -f /home/dvateam128/webapps/team128_app/apache2/conf/httpd.conf'
[Sun Apr 19 00:51:27.902077 2020] [wsgi:error] [pid 25706:tid 139940455544576] [remote 127.0.0.1:34116] FB
[Sun Apr 19 00:51:34.739843 2020] [wsgi:error] [pid 25705:tid 139940455544576] [remote 127.0.0.1:35002] Not Found: /favicon.ico
[Sun Apr 19 00:52:09.839420 2020] [wsgi:error] [pid 25706:tid 139940293764864] [remote 127.0.0.1:39200] FB
[Sun Apr 19 00:52:15.948551 2020] [wsgi:error] [pid 25705:tid 139940363224832] [remote 127.0.0.1:40002] Not Found: /favicon.ico
[Sun Apr 19 00:52:16.579147 2020] [wsgi:error] [pid 25705:tid 139940455544576] [remote 127.0.0.1:40216] FB
[Sun Apr 19 00:52:23.369321 2020] [wsgi:error] [pid 25706:tid 139940455544576] [remote 127.0.0.1:41152] Not Found: /favicon.ico
[Sun Apr 19 00:52:32.921580 2020] [wsgi:error] [pid 25705:tid 139940363224832] [remote 127.0.0.1:42212] FB
[Sun Apr 19 00:52:44.242237 2020] [wsgi:error] [pid 25706:tid 139940293764864] [remote 127.0.0.1:43800] TSLA
[Sun Apr 19 01:03:29.789854 2020] [wsgi:error] [pid 25705:tid 139940455544576] [remote 127.0.0.1:46736] FB
[Sun Apr 19 01:03:51.931841 2020] [wsgi:error] [pid 25706:tid 139940455544576] [remote 127.0.0.1:49864] Not Found: /
[Sun Apr 19 01:03:53.830001 2020] [wsgi:error] [pid 25705:tid 139940363224832] [remote 127.0.0.1:50102] Not Found: /
[Sun Apr 19 01:50:56.399559 2020] [wsgi:error] [pid 25705:tid 139940455544576] [remote 127.0.0.1:48850] FB
[Sun Apr 19 01:52:00.769346 2020] [wsgi:error] [pid 25705:tid 139940363224832] [remote 127.0.0.1:59086] TSLA
[Sun Apr 19 02:01:26.939142 2020] [wsgi:error] [pid 25706:tid 139940455544576] [remote 127.0.0.1:53078] TSLA
[Sun Apr 19 02:06:32.709257 2020] [wsgi:error] [pid 25705:tid 139940455544576] [remote 127.0.0.1:37470] TSLA
[Sun Apr 19 02:07:15.709876 2020] [wsgi:error] [pid 25706:tid 139940293764864] [remote 127.0.0.1:42978] TSLA
[Sun Apr 19 02:07:39.009366 2020] [wsgi:error] [pid 25705:tid 139940363224832] [remote 127.0.0.1:45964] TSLA
[Sun Apr 19 02:08:50.582508 2020] [wsgi:error] [pid 25705:tid 139940455544576] [remote 127.0.0.1:54810] TSLA
[Sun Apr 19 02:10:54.787084 2020] [wsgi:error] [pid 25706:tid 139940455544576] [remote 127.0.0.1:43256] TSLA
[Sun Apr 19 02:11:01.081124 2020] [wsgi:error] [pid 25705:tid 139940363224832] [remote 127.0.0.1:44182] Not Found: /favicon.ico
[Sun Apr 19 02:11:43.686970 2020] [wsgi:error] [pid 25706:tid 139940293764864] [remote 127.0.0.1:49612] TSLA
[Sun Apr 19 02:18:20.098213 2020] [wsgi:error] [pid 25705:tid 139940455544576] [remote 127.0.0.1:42474] TSLA
[Sun Apr 19 02:44:42.859616 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00298: SIGHUP received.  Attempting to restart
[Sun Apr 19 02:44:43.058753 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00292: Apache/2.4.41 (Unix) mod_wsgi/4.7.1 Python/3.7 configured -- resuming normal operations
[Sun Apr 19 02:44:43.058784 2020] [core:notice] [pid 32761:tid 139940535924608] AH00094: Command line: '/home/dvateam128/webapps/team128_app/apache2/bin/httpd.worker -f /home/dvateam128/webapps/team128_app/apache2/conf/httpd.conf'
[Sun Apr 19 02:44:55.896092 2020] [wsgi:error] [pid 48312:tid 139940455544576] [remote 127.0.0.1:35306] AAPL
[Sun Apr 19 02:45:02.748554 2020] [wsgi:error] [pid 48311:tid 139940455544576] [remote 127.0.0.1:36158] Not Found: /favicon.ico
[Sun Apr 19 02:55:30.983008 2020] [wsgi:error] [pid 48312:tid 139940287756032] [remote 127.0.0.1:54400] TSLA
[Sun Apr 19 02:57:52.513621 2020] [wsgi:error] [pid 48311:tid 139940455544576] [remote 127.0.0.1:42906] TSLA
[Sun Apr 19 02:57:58.818464 2020] [wsgi:error] [pid 48311:tid 139940363224832] [remote 127.0.0.1:43716] Not Found: /favicon.ico
[Sun Apr 19 03:19:24.968630 2020] [wsgi:error] [pid 48312:tid 139940455544576] [remote 127.0.0.1:35280] TSLA
[Sun Apr 19 03:20:44.188101 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00298: SIGHUP received.  Attempting to restart
[Sun Apr 19 03:20:44.580810 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00292: Apache/2.4.41 (Unix) mod_wsgi/4.7.1 Python/3.7 configured -- resuming normal operations
[Sun Apr 19 03:20:44.580836 2020] [core:notice] [pid 32761:tid 139940535924608] AH00094: Command line: '/home/dvateam128/webapps/team128_app/apache2/bin/httpd.worker -f /home/dvateam128/webapps/team128_app/apache2/conf/httpd.conf'
[Sun Apr 19 03:20:58.409315 2020] [wsgi:error] [pid 17151:tid 139940455544576] [remote 127.0.0.1:47800] AAPL
[Sun Apr 19 03:21:09.842676 2020] [wsgi:error] [pid 17152:tid 139940455544576] [remote 127.0.0.1:49396] AAPL
[Sun Apr 19 03:21:16.000460 2020] [wsgi:error] [pid 17151:tid 139940293764864] [remote 127.0.0.1:50106] Not Found: /favicon.ico
[Sun Apr 19 04:08:35.410188 2020] [wsgi:error] [pid 17152:tid 139940363224832] [remote 127.0.0.1:58286] AAPL
[Sun Apr 19 04:29:16.190110 2020] [wsgi:error] [pid 17151:tid 139940455544576] [remote 127.0.0.1:41888] 
[Sun Apr 19 04:35:07.406390 2020] [wsgi:error] [pid 17151:tid 139940293764864] [remote 127.0.0.1:54396] TSLA
[Sun Apr 19 04:36:59.469245 2020] [wsgi:error] [pid 17152:tid 139940455544576] [remote 127.0.0.1:40574] FB
[Sun Apr 19 04:38:03.319415 2020] [wsgi:error] [pid 17151:tid 139940455544576] [remote 127.0.0.1:48586] TSLA
[Sun Apr 19 04:58:13.093318 2020] [wsgi:error] [pid 17152:tid 139940363224832] [remote 127.0.0.1:56964] Not Found: /api/
[Sun Apr 19 04:58:18.512384 2020] [wsgi:error] [pid 17152:tid 139940455544576] [remote 127.0.0.1:57652] Not Found: /api/
[Sun Apr 19 04:58:18.518063 2020] [wsgi:error] [pid 17151:tid 139940293764864] [remote 127.0.0.1:57650] Not Found: /robots.txt
[Sun Apr 19 04:58:18.699121 2020] [wsgi:error] [pid 17151:tid 139940455544576] [remote 127.0.0.1:57670] Not Found: /favicon.ico
[Sun Apr 19 05:00:33.637395 2020] [wsgi:error] [pid 17152:tid 139940363224832] [remote 127.0.0.1:47586] Not Found: /api/symbol/example
[Sun Apr 19 05:58:42.977684 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00298: SIGHUP received.  Attempting to restart
[Sun Apr 19 05:58:43.176172 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00292: Apache/2.4.41 (Unix) mod_wsgi/4.7.1 Python/3.7 configured -- resuming normal operations
[Sun Apr 19 05:58:43.176210 2020] [core:notice] [pid 32761:tid 139940535924608] AH00094: Command line: '/home/dvateam128/webapps/team128_app/apache2/bin/httpd.worker -f /home/dvateam128/webapps/team128_app/apache2/conf/httpd.conf'
[Sun Apr 19 05:59:19.721913 2020] [wsgi:error] [pid 3143:tid 139940455544576] [remote 127.0.0.1:40116] Not Found: /api/analysis/example
[Sun Apr 19 05:59:32.065589 2020] [wsgi:error] [pid 3144:tid 139940455544576] [remote 127.0.0.1:41916] Internal Server Error: /api/api/analysis/example
[Sun Apr 19 05:59:32.065632 2020] [wsgi:error] [pid 3144:tid 139940455544576] [remote 127.0.0.1:41916] Traceback (most recent call last):
[Sun Apr 19 05:59:32.065637 2020] [wsgi:error] [pid 3144:tid 139940455544576] [remote 127.0.0.1:41916]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/handlers/exception.py", line 34, in inner
[Sun Apr 19 05:59:32.065641 2020] [wsgi:error] [pid 3144:tid 139940455544576] [remote 127.0.0.1:41916]     response = get_response(request)
[Sun Apr 19 05:59:32.065645 2020] [wsgi:error] [pid 3144:tid 139940455544576] [remote 127.0.0.1:41916]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/handlers/base.py", line 115, in _get_response
[Sun Apr 19 05:59:32.065649 2020] [wsgi:error] [pid 3144:tid 139940455544576] [remote 127.0.0.1:41916]     response = self.process_exception_by_middleware(e, request)
[Sun Apr 19 05:59:32.065653 2020] [wsgi:error] [pid 3144:tid 139940455544576] [remote 127.0.0.1:41916]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/handlers/base.py", line 113, in _get_response
[Sun Apr 19 05:59:32.065670 2020] [wsgi:error] [pid 3144:tid 139940455544576] [remote 127.0.0.1:41916]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Sun Apr 19 05:59:32.065674 2020] [wsgi:error] [pid 3144:tid 139940455544576] [remote 127.0.0.1:41916]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/views/decorators/csrf.py", line 54, in wrapped_view
[Sun Apr 19 05:59:32.065678 2020] [wsgi:error] [pid 3144:tid 139940455544576] [remote 127.0.0.1:41916]     return view_func(*args, **kwargs)
[Sun Apr 19 05:59:32.065681 2020] [wsgi:error] [pid 3144:tid 139940455544576] [remote 127.0.0.1:41916]   File "/home/dvateam128/webapps/team128_app/myproject/stocks/views.py", line 93, in example
[Sun Apr 19 05:59:32.065685 2020] [wsgi:error] [pid 3144:tid 139940455544576] [remote 127.0.0.1:41916]     fp = os.path.abspath(os.path.dirname(
[Sun Apr 19 05:59:32.065688 2020] [wsgi:error] [pid 3144:tid 139940455544576] [remote 127.0.0.1:41916] NameError: name 'os' is not defined
[Sun Apr 19 06:00:03.627874 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00298: SIGHUP received.  Attempting to restart
[Sun Apr 19 06:00:04.022658 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00292: Apache/2.4.41 (Unix) mod_wsgi/4.7.1 Python/3.7 configured -- resuming normal operations
[Sun Apr 19 06:00:04.022699 2020] [core:notice] [pid 32761:tid 139940535924608] AH00094: Command line: '/home/dvateam128/webapps/team128_app/apache2/bin/httpd.worker -f /home/dvateam128/webapps/team128_app/apache2/conf/httpd.conf'
[Sun Apr 19 06:00:06.449184 2020] [wsgi:error] [pid 8339:tid 139940455544576] [remote 127.0.0.1:45136] Internal Server Error: /api/api/analysis/example
[Sun Apr 19 06:00:06.449232 2020] [wsgi:error] [pid 8339:tid 139940455544576] [remote 127.0.0.1:45136] Traceback (most recent call last):
[Sun Apr 19 06:00:06.449237 2020] [wsgi:error] [pid 8339:tid 139940455544576] [remote 127.0.0.1:45136]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/handlers/exception.py", line 34, in inner
[Sun Apr 19 06:00:06.449241 2020] [wsgi:error] [pid 8339:tid 139940455544576] [remote 127.0.0.1:45136]     response = get_response(request)
[Sun Apr 19 06:00:06.449244 2020] [wsgi:error] [pid 8339:tid 139940455544576] [remote 127.0.0.1:45136]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/handlers/base.py", line 115, in _get_response
[Sun Apr 19 06:00:06.449248 2020] [wsgi:error] [pid 8339:tid 139940455544576] [remote 127.0.0.1:45136]     response = self.process_exception_by_middleware(e, request)
[Sun Apr 19 06:00:06.449252 2020] [wsgi:error] [pid 8339:tid 139940455544576] [remote 127.0.0.1:45136]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/handlers/base.py", line 113, in _get_response
[Sun Apr 19 06:00:06.449256 2020] [wsgi:error] [pid 8339:tid 139940455544576] [remote 127.0.0.1:45136]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Sun Apr 19 06:00:06.449259 2020] [wsgi:error] [pid 8339:tid 139940455544576] [remote 127.0.0.1:45136]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/views/decorators/csrf.py", line 54, in wrapped_view
[Sun Apr 19 06:00:06.449263 2020] [wsgi:error] [pid 8339:tid 139940455544576] [remote 127.0.0.1:45136]     return view_func(*args, **kwargs)
[Sun Apr 19 06:00:06.449266 2020] [wsgi:error] [pid 8339:tid 139940455544576] [remote 127.0.0.1:45136]   File "/home/dvateam128/webapps/team128_app/myproject/stocks/views.py", line 95, in example
[Sun Apr 19 06:00:06.449269 2020] [wsgi:error] [pid 8339:tid 139940455544576] [remote 127.0.0.1:45136]     with open(fp, 'r') as f:
[Sun Apr 19 06:00:06.449272 2020] [wsgi:error] [pid 8339:tid 139940455544576] [remote 127.0.0.1:45136] FileNotFoundError: [Errno 2] No such file or directory: '/home/dvateam128/webapps/team128_app/myproject/stocks/analysis/output_18Apr.json'
[Sun Apr 19 06:00:43.312900 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00298: SIGHUP received.  Attempting to restart
[Sun Apr 19 06:00:43.417826 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00292: Apache/2.4.41 (Unix) mod_wsgi/4.7.1 Python/3.7 configured -- resuming normal operations
[Sun Apr 19 06:00:43.417846 2020] [core:notice] [pid 32761:tid 139940535924608] AH00094: Command line: '/home/dvateam128/webapps/team128_app/apache2/bin/httpd.worker -f /home/dvateam128/webapps/team128_app/apache2/conf/httpd.conf'
[Sun Apr 19 06:00:49.659731 2020] [wsgi:error] [pid 12732:tid 139940455544576] [remote 127.0.0.1:49520] Internal Server Error: /api/api/analysis/example
[Sun Apr 19 06:00:49.659785 2020] [wsgi:error] [pid 12732:tid 139940455544576] [remote 127.0.0.1:49520] Traceback (most recent call last):
[Sun Apr 19 06:00:49.659790 2020] [wsgi:error] [pid 12732:tid 139940455544576] [remote 127.0.0.1:49520]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/handlers/exception.py", line 34, in inner
[Sun Apr 19 06:00:49.659794 2020] [wsgi:error] [pid 12732:tid 139940455544576] [remote 127.0.0.1:49520]     response = get_response(request)
[Sun Apr 19 06:00:49.659797 2020] [wsgi:error] [pid 12732:tid 139940455544576] [remote 127.0.0.1:49520]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/handlers/base.py", line 115, in _get_response
[Sun Apr 19 06:00:49.659808 2020] [wsgi:error] [pid 12732:tid 139940455544576] [remote 127.0.0.1:49520]     response = self.process_exception_by_middleware(e, request)
[Sun Apr 19 06:00:49.659814 2020] [wsgi:error] [pid 12732:tid 139940455544576] [remote 127.0.0.1:49520]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/handlers/base.py", line 113, in _get_response
[Sun Apr 19 06:00:49.659818 2020] [wsgi:error] [pid 12732:tid 139940455544576] [remote 127.0.0.1:49520]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Sun Apr 19 06:00:49.659822 2020] [wsgi:error] [pid 12732:tid 139940455544576] [remote 127.0.0.1:49520]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/views/decorators/csrf.py", line 54, in wrapped_view
[Sun Apr 19 06:00:49.659826 2020] [wsgi:error] [pid 12732:tid 139940455544576] [remote 127.0.0.1:49520]     return view_func(*args, **kwargs)
[Sun Apr 19 06:00:49.659829 2020] [wsgi:error] [pid 12732:tid 139940455544576] [remote 127.0.0.1:49520]   File "/home/dvateam128/webapps/team128_app/myproject/stocks/views.py", line 96, in example
[Sun Apr 19 06:00:49.659833 2020] [wsgi:error] [pid 12732:tid 139940455544576] [remote 127.0.0.1:49520]     with open(fp, 'r') as f:
[Sun Apr 19 06:00:49.659836 2020] [wsgi:error] [pid 12732:tid 139940455544576] [remote 127.0.0.1:49520] FileNotFoundError: [Errno 2] No such file or directory: '/home/dvateam128/webapps/team128_app/myproject/stocks/analysis/output_18Apr.json'
[Sun Apr 19 06:03:36.416461 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00298: SIGHUP received.  Attempting to restart
[Sun Apr 19 06:03:36.614779 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00292: Apache/2.4.41 (Unix) mod_wsgi/4.7.1 Python/3.7 configured -- resuming normal operations
[Sun Apr 19 06:03:36.614810 2020] [core:notice] [pid 32761:tid 139940535924608] AH00094: Command line: '/home/dvateam128/webapps/team128_app/apache2/bin/httpd.worker -f /home/dvateam128/webapps/team128_app/apache2/conf/httpd.conf'
[Sun Apr 19 06:03:42.805676 2020] [wsgi:error] [pid 22109:tid 139940447151872] [remote 127.0.0.1:37352] Not Found: /api/analysis/example
[Sun Apr 19 15:21:55.685833 2020] [wsgi:error] [pid 22110:tid 139940455544576] [remote 127.0.0.1:57998] Not Found: /api/analysis/example
[Sun Apr 19 15:21:55.872171 2020] [wsgi:error] [pid 22109:tid 139940293764864] [remote 127.0.0.1:58118] Not Found: /favicon.ico
[Sun Apr 19 15:22:11.631600 2020] [wsgi:error] [pid 22110:tid 139940363224832] [remote 127.0.0.1:60370] Not Found: /api/analysis/example
[Sun Apr 19 15:42:08.129921 2020] [wsgi:error] [pid 22109:tid 139940447151872] [remote 127.0.0.1:34862] Not Found: /api/analysis/example
[Sun Apr 19 15:45:47.781634 2020] [wsgi:error] [pid 22110:tid 139940455544576] [remote 127.0.0.1:41818] Not Found: /api/
[Sun Apr 19 18:18:23.988733 2020] [wsgi:error] [pid 22110:tid 139940363224832] [remote 127.0.0.1:52264] Not Found: /api/
[Sun Apr 19 18:18:24.213252 2020] [wsgi:error] [pid 22109:tid 139940293764864] [remote 127.0.0.1:52314] Not Found: /favicon.ico
[Sun Apr 19 18:18:39.349525 2020] [wsgi:error] [pid 22110:tid 139940455544576] [remote 127.0.0.1:54626] Not Found: /api/ analysis$
[Sun Apr 19 18:18:41.387425 2020] [wsgi:error] [pid 22110:tid 139940363224832] [remote 127.0.0.1:54988] FB
[Sun Apr 19 18:18:46.533336 2020] [wsgi:error] [pid 22109:tid 139940447151872] [remote 127.0.0.1:55762] FB
[Sun Apr 19 18:20:00.401367 2020] [wsgi:error] [pid 22110:tid 139940455544576] [remote 127.0.0.1:38976] AAPL
[Sun Apr 19 18:30:22.678788 2020] [wsgi:error] [pid 22109:tid 139940293764864] [remote 127.0.0.1:59020] AAPL
[Sun Apr 19 18:33:15.729218 2020] [wsgi:error] [pid 22110:tid 139940363224832] [remote 127.0.0.1:60570] AAPL
[Sun Apr 19 18:33:21.827386 2020] [wsgi:error] [pid 22109:tid 139940447151872] [remote 127.0.0.1:33380] Not Found: /favicon.ico
[Sun Apr 19 18:35:44.899087 2020] [wsgi:error] [pid 22109:tid 139940293764864] [remote 127.0.0.1:57212] Not Found: /api/analysis/example
[Sun Apr 19 19:02:28.447821 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00298: SIGHUP received.  Attempting to restart
[Sun Apr 19 19:02:28.649669 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00292: Apache/2.4.41 (Unix) mod_wsgi/4.7.1 Python/3.7 configured -- resuming normal operations
[Sun Apr 19 19:02:28.649692 2020] [core:notice] [pid 32761:tid 139940535924608] AH00094: Command line: '/home/dvateam128/webapps/team128_app/apache2/bin/httpd.worker -f /home/dvateam128/webapps/team128_app/apache2/conf/httpd.conf'
[Sun Apr 19 19:02:42.708147 2020] [wsgi:error] [pid 7167:tid 139940455544576] [remote 127.0.0.1:41502] AAPL
[Sun Apr 19 19:03:21.971328 2020] [wsgi:error] [pid 7169:tid 139940455544576] [remote 127.0.0.1:47330] AAPL
[Sun Apr 19 19:03:27.841715 2020] [wsgi:error] [pid 7167:tid 139940293764864] [remote 127.0.0.1:48234] Not Found: /favicon.ico
[Sun Apr 19 19:08:01.303704 2020] [wsgi:error] [pid 7169:tid 139940455544576] [remote 127.0.0.1:60492] AAPL
[Sun Apr 19 19:08:07.481083 2020] [wsgi:error] [pid 7167:tid 139940455544576] [remote 127.0.0.1:33192] Not Found: /favicon.ico
[Sun Apr 19 19:08:13.773583 2020] [wsgi:error] [pid 7169:tid 139940363224832] [remote 127.0.0.1:34112] AAPL
[Sun Apr 19 19:08:54.140968 2020] [wsgi:error] [pid 7167:tid 139940455544576] [remote 127.0.0.1:39778] Not Found: /favicon.ico
[Sun Apr 19 19:19:31.755634 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00298: SIGHUP received.  Attempting to restart
[Sun Apr 19 19:19:31.951834 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00292: Apache/2.4.41 (Unix) mod_wsgi/4.7.1 Python/3.7 configured -- resuming normal operations
[Sun Apr 19 19:19:31.951876 2020] [core:notice] [pid 32761:tid 139940535924608] AH00094: Command line: '/home/dvateam128/webapps/team128_app/apache2/bin/httpd.worker -f /home/dvateam128/webapps/team128_app/apache2/conf/httpd.conf'
[Sun Apr 19 19:19:38.069049 2020] [wsgi:error] [pid 34630:tid 139940455544576] [remote 127.0.0.1:41716] AAPL
[Sun Apr 19 19:20:00.409448 2020] [wsgi:error] [pid 34631:tid 139940455544576] [remote 127.0.0.1:45160] Internal Server Error: /api/matt
[Sun Apr 19 19:20:00.409499 2020] [wsgi:error] [pid 34631:tid 139940455544576] [remote 127.0.0.1:45160] Traceback (most recent call last):
[Sun Apr 19 19:20:00.409504 2020] [wsgi:error] [pid 34631:tid 139940455544576] [remote 127.0.0.1:45160]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/handlers/exception.py", line 34, in inner
[Sun Apr 19 19:20:00.409508 2020] [wsgi:error] [pid 34631:tid 139940455544576] [remote 127.0.0.1:45160]     response = get_response(request)
[Sun Apr 19 19:20:00.409521 2020] [wsgi:error] [pid 34631:tid 139940455544576] [remote 127.0.0.1:45160]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/handlers/base.py", line 115, in _get_response
[Sun Apr 19 19:20:00.409525 2020] [wsgi:error] [pid 34631:tid 139940455544576] [remote 127.0.0.1:45160]     response = self.process_exception_by_middleware(e, request)
[Sun Apr 19 19:20:00.409529 2020] [wsgi:error] [pid 34631:tid 139940455544576] [remote 127.0.0.1:45160]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/handlers/base.py", line 113, in _get_response
[Sun Apr 19 19:20:00.409533 2020] [wsgi:error] [pid 34631:tid 139940455544576] [remote 127.0.0.1:45160]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Sun Apr 19 19:20:00.409537 2020] [wsgi:error] [pid 34631:tid 139940455544576] [remote 127.0.0.1:45160]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/views/decorators/csrf.py", line 54, in wrapped_view
[Sun Apr 19 19:20:00.409541 2020] [wsgi:error] [pid 34631:tid 139940455544576] [remote 127.0.0.1:45160]     return view_func(*args, **kwargs)
[Sun Apr 19 19:20:00.409544 2020] [wsgi:error] [pid 34631:tid 139940455544576] [remote 127.0.0.1:45160]   File "/home/dvateam128/webapps/team128_app/myproject/stocks/views.py", line 110, in matt
[Sun Apr 19 19:20:00.409547 2020] [wsgi:error] [pid 34631:tid 139940455544576] [remote 127.0.0.1:45160]     from stocks.analysis.Price_analysis_json import price_analysis
[Sun Apr 19 19:20:00.409551 2020] [wsgi:error] [pid 34631:tid 139940455544576] [remote 127.0.0.1:45160]   File "/home/dvateam128/webapps/team128_app/myproject/stocks/analysis/Price_analysis_json.py", line 1, in <module>
[Sun Apr 19 19:20:00.409554 2020] [wsgi:error] [pid 34631:tid 139940455544576] [remote 127.0.0.1:45160]     import pandas as pd
[Sun Apr 19 19:20:00.409557 2020] [wsgi:error] [pid 34631:tid 139940455544576] [remote 127.0.0.1:45160] ModuleNotFoundError: No module named 'pandas'
[Sun Apr 19 19:28:48.603655 2020] [wsgi:error] [pid 34630:tid 139940455544576] [remote 127.0.0.1:33602] Not Found: /favicon.ico
[Sun Apr 19 19:31:44.410044 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00298: SIGHUP received.  Attempting to restart
[Sun Apr 19 19:31:44.799774 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00292: Apache/2.4.41 (Unix) mod_wsgi/4.7.1 Python/3.7 configured -- resuming normal operations
[Sun Apr 19 19:31:44.799796 2020] [core:notice] [pid 32761:tid 139940535924608] AH00094: Command line: '/home/dvateam128/webapps/team128_app/apache2/bin/httpd.worker -f /home/dvateam128/webapps/team128_app/apache2/conf/httpd.conf'
[Sun Apr 19 19:31:53.816679 2020] [wsgi:error] [pid 2279:tid 139940455544576] [remote 127.0.0.1:33974] Internal Server Error: /api/matt
[Sun Apr 19 19:31:53.816726 2020] [wsgi:error] [pid 2279:tid 139940455544576] [remote 127.0.0.1:33974] Traceback (most recent call last):
[Sun Apr 19 19:31:53.816730 2020] [wsgi:error] [pid 2279:tid 139940455544576] [remote 127.0.0.1:33974]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/handlers/exception.py", line 34, in inner
[Sun Apr 19 19:31:53.816734 2020] [wsgi:error] [pid 2279:tid 139940455544576] [remote 127.0.0.1:33974]     response = get_response(request)
[Sun Apr 19 19:31:53.816738 2020] [wsgi:error] [pid 2279:tid 139940455544576] [remote 127.0.0.1:33974]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/handlers/base.py", line 115, in _get_response
[Sun Apr 19 19:31:53.816742 2020] [wsgi:error] [pid 2279:tid 139940455544576] [remote 127.0.0.1:33974]     response = self.process_exception_by_middleware(e, request)
[Sun Apr 19 19:31:53.816745 2020] [wsgi:error] [pid 2279:tid 139940455544576] [remote 127.0.0.1:33974]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/handlers/base.py", line 113, in _get_response
[Sun Apr 19 19:31:53.816749 2020] [wsgi:error] [pid 2279:tid 139940455544576] [remote 127.0.0.1:33974]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Sun Apr 19 19:31:53.816765 2020] [wsgi:error] [pid 2279:tid 139940455544576] [remote 127.0.0.1:33974]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/views/decorators/csrf.py", line 54, in wrapped_view
[Sun Apr 19 19:31:53.816769 2020] [wsgi:error] [pid 2279:tid 139940455544576] [remote 127.0.0.1:33974]     return view_func(*args, **kwargs)
[Sun Apr 19 19:31:53.816772 2020] [wsgi:error] [pid 2279:tid 139940455544576] [remote 127.0.0.1:33974]   File "/home/dvateam128/webapps/team128_app/myproject/stocks/views.py", line 110, in matt
[Sun Apr 19 19:31:53.816775 2020] [wsgi:error] [pid 2279:tid 139940455544576] [remote 127.0.0.1:33974]     from stocks.analysis.Price_analysis_json import price_analysis
[Sun Apr 19 19:31:53.816778 2020] [wsgi:error] [pid 2279:tid 139940455544576] [remote 127.0.0.1:33974]   File "/home/dvateam128/webapps/team128_app/myproject/stocks/analysis/Price_analysis_json.py", line 1, in <module>
[Sun Apr 19 19:31:53.816782 2020] [wsgi:error] [pid 2279:tid 139940455544576] [remote 127.0.0.1:33974]     import pandas as pd
[Sun Apr 19 19:31:53.816784 2020] [wsgi:error] [pid 2279:tid 139940455544576] [remote 127.0.0.1:33974] ModuleNotFoundError: No module named 'pandas'
[Sun Apr 19 19:41:45.703602 2020] [wsgi:error] [pid 2279:tid 139940293764864] [remote 127.0.0.1:47614] Not Found: /favicon.ico
[Sun Apr 19 20:10:06.495026 2020] [wsgi:error] [pid 2278:tid 139940363224832] [remote 127.0.0.1:58978] Internal Server Error: /api/matt
[Sun Apr 19 20:10:06.495084 2020] [wsgi:error] [pid 2278:tid 139940363224832] [remote 127.0.0.1:58978] Traceback (most recent call last):
[Sun Apr 19 20:10:06.495088 2020] [wsgi:error] [pid 2278:tid 139940363224832] [remote 127.0.0.1:58978]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/handlers/exception.py", line 34, in inner
[Sun Apr 19 20:10:06.495093 2020] [wsgi:error] [pid 2278:tid 139940363224832] [remote 127.0.0.1:58978]     response = get_response(request)
[Sun Apr 19 20:10:06.495096 2020] [wsgi:error] [pid 2278:tid 139940363224832] [remote 127.0.0.1:58978]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/handlers/base.py", line 115, in _get_response
[Sun Apr 19 20:10:06.495100 2020] [wsgi:error] [pid 2278:tid 139940363224832] [remote 127.0.0.1:58978]     response = self.process_exception_by_middleware(e, request)
[Sun Apr 19 20:10:06.495104 2020] [wsgi:error] [pid 2278:tid 139940363224832] [remote 127.0.0.1:58978]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/core/handlers/base.py", line 113, in _get_response
[Sun Apr 19 20:10:06.495107 2020] [wsgi:error] [pid 2278:tid 139940363224832] [remote 127.0.0.1:58978]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Sun Apr 19 20:10:06.495111 2020] [wsgi:error] [pid 2278:tid 139940363224832] [remote 127.0.0.1:58978]   File "/home/dvateam128/webapps/team128_app/lib/python3.7/Django-2.2.11-py3.7.egg/django/views/decorators/csrf.py", line 54, in wrapped_view
[Sun Apr 19 20:10:06.495114 2020] [wsgi:error] [pid 2278:tid 139940363224832] [remote 127.0.0.1:58978]     return view_func(*args, **kwargs)
[Sun Apr 19 20:10:06.495117 2020] [wsgi:error] [pid 2278:tid 139940363224832] [remote 127.0.0.1:58978]   File "/home/dvateam128/webapps/team128_app/myproject/stocks/views.py", line 110, in matt
[Sun Apr 19 20:10:06.495120 2020] [wsgi:error] [pid 2278:tid 139940363224832] [remote 127.0.0.1:58978]     from stocks.analysis.Price_analysis_json import price_analysis
[Sun Apr 19 20:10:06.495124 2020] [wsgi:error] [pid 2278:tid 139940363224832] [remote 127.0.0.1:58978]   File "/home/dvateam128/webapps/team128_app/myproject/stocks/analysis/Price_analysis_json.py", line 6, in <module>
[Sun Apr 19 20:10:06.495127 2020] [wsgi:error] [pid 2278:tid 139940363224832] [remote 127.0.0.1:58978]     from sklearn.ensemble import RandomForestClassifier
[Sun Apr 19 20:10:06.495147 2020] [wsgi:error] [pid 2278:tid 139940363224832] [remote 127.0.0.1:58978] ModuleNotFoundError: No module named 'sklearn'
[Sun Apr 19 20:11:55.028371 2020] [wsgi:error] [pid 2280:tid 139940360873728] [client 127.0.0.1:37382] Timeout when reading response headers from daemon process 'team128_app': /home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py
[Sun Apr 19 20:13:05.377148 2020] [wsgi:error] [pid 2280:tid 139940466579200] [client 127.0.0.1:47730] Timeout when reading response headers from daemon process 'team128_app': /home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py
[Sun Apr 19 20:23:29.597993 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00298: SIGHUP received.  Attempting to restart
[Sun Apr 19 20:23:29.990579 2020] [mpm_worker:notice] [pid 32761:tid 139940535924608] AH00292: Apache/2.4.41 (Unix) mod_wsgi/4.7.1 Python/3.7 configured -- resuming normal operations
[Sun Apr 19 20:23:29.990615 2020] [core:notice] [pid 32761:tid 139940535924608] AH00094: Command line: '/home/dvateam128/webapps/team128_app/apache2/bin/httpd.worker -f /home/dvateam128/webapps/team128_app/apache2/conf/httpd.conf'
[Sun Apr 19 20:23:58.062129 2020] [wsgi:error] [pid 13140:tid 139940455544576] [remote 127.0.0.1:34462] Not Found: /favicon.ico
[Sun Apr 19 20:24:08.191983 2020] [wsgi:error] [pid 13139:tid 139940293732096] [remote 127.0.0.1:34732] hello
[Sun Apr 19 20:24:09.029982 2020] [wsgi:error] [pid 13139:tid 139940293732096] [remote 127.0.0.1:34732] 
[Sun Apr 19 20:24:09.030019 2020] [wsgi:error] [pid 13139:tid 139940293732096] [remote 127.0.0.1:34732] Rows to drop:
[Sun Apr 19 20:24:09.030058 2020] [wsgi:error] [pid 13139:tid 139940293732096] [remote 127.0.0.1:34732]  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251]
[Sun Apr 19 20:24:09.031917 2020] [wsgi:error] [pid 13139:tid 139940293732096] [remote 127.0.0.1:34732] 
[Sun Apr 19 20:24:09.031940 2020] [wsgi:error] [pid 13139:tid 139940293732096] [remote 127.0.0.1:34732] df_anal:
[Sun Apr 19 20:24:09.067538 2020] [wsgi:error] [pid 13139:tid 139940293732096] [remote 127.0.0.1:34732]            Date  term_5  term_15  ...  ease_of_move  williams_r  rel_strength
[Sun Apr 19 20:24:09.067580 2020] [wsgi:error] [pid 13139:tid 139940293732096] [remote 127.0.0.1:34732] 43  2019-06-17     5.0      6.0  ...     30.846800  -10.935143     57.334465
[Sun Apr 19 20:24:09.067583 2020] [wsgi:error] [pid 13139:tid 139940293732096] [remote 127.0.0.1:34732] 44  2019-06-18     4.0      5.0  ...     80.071548   -6.129247     63.092304
[Sun Apr 19 20:24:09.067587 2020] [wsgi:error] [pid 13139:tid 139940293732096] [remote 127.0.0.1:34732] 45  2019-06-19     2.0      4.0  ...     10.280372   -8.061292     61.947182
[Sun Apr 19 20:24:09.067590 2020] [wsgi:error] [pid 13139:tid 139940293732096] [remote 127.0.0.1:34732] 46  2019-06-20     2.0      2.0  ...      8.694343   -3.790376     63.882477
[Sun Apr 19 20:24:09.067592 2020] [wsgi:error] [pid 13139:tid 139940293732096] [remote 127.0.0.1:34732] 47  2019-06-21     2.0      5.0  ...      1.016724   -7.861755     62.420357
[Sun Apr 19 20:24:09.067595 2020] [wsgi:error] [pid 13139:tid 139940293732096] [remote 127.0.0.1:34732] ..         ...     ...      ...  ...           ...         ...           ...
[Sun Apr 19 20:24:09.067598 2020] [wsgi:error] [pid 13139:tid 139940293732096] [remote 127.0.0.1:34732] 179 2019-12-30     5.0      6.0  ...    -43.295805   -8.715760     79.598984
[Sun Apr 19 20:24:09.067601 2020] [wsgi:error] [pid 13139:tid 139940293732096] [remote 127.0.0.1:34732] 180 2019-12-31     6.0      6.0  ...     43.581129   -1.200796     80.999276
[Sun Apr 19 20:24:09.067620 2020] [wsgi:error] [pid 13139:tid 139940293732096] [remote 127.0.0.1:34732] 181 2020-01-02     5.0      6.0  ...    100.424884   -0.751224     84.583749
[Sun Apr 19 20:24:09.067624 2020] [wsgi:error] [pid 13139:tid 139940293732096] [remote 127.0.0.1:34732] 182 2020-01-03     6.0      6.0  ...      7.183515  -10.684193     77.703728
[Sun Apr 19 20:24:09.067626 2020] [wsgi:error] [pid 13139:tid 139940293732096] [remote 127.0.0.1:34732] 183 2020-01-06     6.0      6.0  ...    -53.142315   -3.386960     79.183710
[Sun Apr 19 20:24:09.067629 2020] [wsgi:error] [pid 13139:tid 139940293732096] [remote 127.0.0.1:34732] 
[Sun Apr 19 20:24:09.067634 2020] [wsgi:error] [pid 13139:tid 139940293732096] [remote 127.0.0.1:34732] [141 rows x 9 columns]
[Sun Apr 19 20:24:09.067651 2020] [wsgi:error] [pid 13139:tid 139940293732096] [remote 127.0.0.1:34732] 
[Sun Apr 19 20:24:11.821346 2020] [wsgi:error] [pid 13139:tid 139940293732096] [remote 127.0.0.1:34732] {'dates': ['06/17/2019', '06/18/2019', '06/19/2019', '06/20/2019', '06/21/2019', '06/24/2019', '06/25/2019', '06/26/2019', '06/27/2019', '06/28/2019', '07/01/2019', '07/02/2019', '07/03/2019', '07/05/2019', '07/08/2019', '07/09/2019', '07/10/2019', '07/11/2019', '07/12/2019', '07/15/2019', '07/16/2019', '07/17/2019', '07/18/2019', '07/19/2019', '07/22/2019', '07/23/2019', '07/24/2019', '07/25/2019', '07/26/2019', '07/29/2019', '07/30/2019', '07/31/2019', '08/01/2019', '08/02/2019', '08/05/2019', '08/06/2019', '08/07/2019', '08/08/2019', '08/09/2019', '08/12/2019', '08/13/2019', '08/14/2019', '08/15/2019', '08/16/2019', '08/19/2019', '08/20/2019', '08/21/2019', '08/22/2019', '08/23/2019', '08/26/2019', '08/27/2019', '08/28/2019', '08/29/2019', '08/30/2019', '09/03/2019', '09/04/2019', '09/05/2019', '09/06/2019', '09/09/2019', '09/10/2019', '09/11/2019', '09/12/2019', '09/13/2019', '09/16/2019', '09/17/2019', '09/18/2019', '09/19/2019', '09/20/2019', '09/23/2019', '09/24/2019', '09/25/2019', '09/26/2019', '09/27/2019', '09/30/2019', '10/01/2019', '10/02/2019', '10/03/2019', '10/04/2019', '10/07/2019', '10/08/2019', '10/09/2019', '10/10/2019', '10/11/2019', '10/14/2019', '10/15/2019', '10/16/2019', '10/17/2019', '10/18/2019', '10/21/2019', '10/22/2019', '10/23/2019', '10/24/2019', '10/25/2019', '10/28/2019', '10/29/2019', '10/30/2019', '10/31/2019', '11/01/2019', '11/04/2019', '11/05/2019', '11/06/2019', '11/07/2019', '11/08/2019', '11/11/2019', '11/12/2019', '11/13/2019', '11/14/2019', '11/15/2019', '11/18/2019', '11/19/2019', '11/20/2019', '11/21/2019', '11/22/2019', '11/25/2019', '11/26/2019', '11/27/2019', '11/29/2019', '12/02/2019', '12/03/2019', '12/04/2019', '12/05/2019', '12/06/2019', '12/09/2019', '12/10/2019', '12/11/2019', '12/12/2019', '12/13/2019', '12/16/2019', '12/17/2019', '12/18/2019', '12/19/2019', '12/20/2019', '12/23/2019', '12/24/2019', '12/26/2019', '12/27/2019', '12/30/2019', '12/31/2019', '01/02/2020', '01/03/2020', '01/06/2020'], 'daily_ret': [0.0, 0.023518489865387605, -0.0029226505416980806, 0.008035578915449555, -0.0034092048531034133, -0.0010061374383740246, -0.015157619095578705, 0.02162908421537055, -0.00030030030030031167, -0.009111845399018832, 0.01834074373484248, 0.005854626643512668, 0.008286884032950264, -0.0008805831417249979, -0.020614013612103903, 0.0060993900609938945, 0.009888690121248165, -0.007282389411012104, 0.007682775712515546, 0.009394982784062944, -0.0034598703766873344, -0.005623471882640615, 0.011359724612736672, -0.014927550325780381, 0.02285404017967321, 0.007817778206736823, -0.0008140203026240946, -0.007907221929362043, 0.0034779248381798804, 0.009338596322325973, -0.0042922548645555406, 0.020404253280965567, -0.021639128802102822, -0.021158182603272065, -0.052347809038329605, 0.018930381710975466, 0.010355329949238538, 0.022055868167202647, -0.011994297792852566, -0.0025374396736156987, 0.04234836392657627, -0.02976503804373833, -0.004981504315659634, 0.023594725884802173, 0.018644067796610143, 4.753981459481496e-05, 0.010838562464346703, -0.0008465011286680701, -0.04622046502871139, 0.018999210422424116, -0.011283839411109556, 0.006710423197492185, 0.016931834768646865, -0.001291804219893698, -0.01456357190763639, 0.016966456003889203, 0.019551603805153226, -9.377344336088819e-05, 0.004267091812810638, 0.011813045711350802, 0.031795108444854704, -0.002258598327295476, -0.019432055046282842, 0.005257142857142883, 0.003638017280582005, 0.009379247847757234, -0.008124971944157662, -0.01461803041274447, 0.004546915905020021, -0.004754937820043856, 0.015389562660786449, -0.005157670904402184, -0.004866069398335501, 0.023535325838588823, 0.0027682278876635467, -0.02506790150941714, 0.008494702228717507, 0.02803188117018385, 0.0002202546143342204, -0.011714965207434144, 0.011720142602495523, 0.013478394925780743, 0.02659828762658092, -0.0014393971466068474, -0.0023317929367872615, -0.004037055923848329, 0.003882749498655957, 0.004802788167290018, 0.017342751998646395, -0.002286807201363698, 0.013418903150525083, 0.001644872111193378, 0.012316282124969208, 0.010017033011598665, -0.023127885966673437, -0.00012330963048214533, 0.02260955356408781, 0.028380768612317104, 0.006567117504495375, -0.0014368932038835128, 0.00042779916773621763, 0.008513450474265268, 0.0027367690706548184, 0.007918812946874769, -0.0009153318077803551, 0.009581615513819086, -0.006919499376110866, 0.011879378617118507, 0.005042143287176519, -0.0030325720703856317, -0.01164144353899892, -0.004483453018731741, -0.0008778290904927987, 0.017533807013522928, -0.007808687164470414, 0.013432214612735837, -0.0022028076463559403, -0.011562207670720206, -0.01783010296789838, 0.008826363461167934, 0.014671047604492912, 0.019316213570298953, -0.014000221639392576, 0.005844447774614125, 0.008529499404052307, 0.00254828821509029, 0.013593162896927717, 0.01711793567145207, 0.001965268348459985, -0.002389358439428037, 0.001000929434474772, -0.0020712806228125997, 0.016318350987689672, 0.0009507042253520487, 0.019840292679495, -0.0003794280983754049, 0.005935127674258007, 0.007306531284302949, 0.02281627788183227, -0.009721991010487816, 0.007968261439666492], 'cum_return': [0.0, 0.023518489865387605, 0.020595839323689524, 0.02863141823913908, 0.025222213386035666, 0.02421607594766164, 0.009058456852082935, 0.030687541067453486, 0.030387240767153174, 0.02127539536813434, 0.03961613910297682, 0.04547076574648949, 0.05375764977943975, 0.052877066637714756, 0.032263053025610854, 0.03836244308660475, 0.04825113320785291, 0.040968743796840804, 0.04865151950935635, 0.058046502293419296, 0.054586631916731965, 0.048963160034091346, 0.060322884646828015, 0.045395334321047635, 0.06824937450072084, 0.07606715270745766, 0.07525313240483357, 0.06734591047547153, 0.07082383531365141, 0.08016243163597739, 0.07587017677142185, 0.09627443005238742, 0.0746353012502846, 0.05347711864701253, 0.0011293096086829255, 0.02005969131965839, 0.03041502126889693, 0.05247088943609958, 0.04047659164324702, 0.03793915196963132, 0.08028751589620758, 0.05052247785246926, 0.04554097353680962, 0.0691356994216118, 0.08777976721822194, 0.08782730703281676, 0.09866586949716347, 0.09781936836849539, 0.051598903339784, 0.07059811376220812, 0.05931427435109857, 0.06602469754859075, 0.08295653231723761, 0.08166472809734392, 0.06710115618970752, 0.08406761219359672, 0.10361921599874994, 0.10352544255538905, 0.10779253436819969, 0.1196055800795505, 0.1514006885244052, 0.14914209019710972, 0.12971003515082688, 0.13496717800796976, 0.13860519528855175, 0.14798444313630899, 0.13985947119215134, 0.12524144077940685, 0.12978835668442687, 0.12503341886438302, 0.14042298152516947, 0.13526531062076727, 0.13039924122243177, 0.1539345670610206, 0.15670279494868414, 0.131634893439267, 0.1401295956679845, 0.16816147683816834, 0.16838173145250257, 0.15666676624506842, 0.16838690884756394, 0.18186530377334467, 0.2084635913999256, 0.20702419425331875, 0.2046924013165315, 0.20065534539268315, 0.20453809489133912, 0.20934088305862913, 0.22668363505727554, 0.22439682785591183, 0.2378157310064369, 0.2394606031176303, 0.2517768852425995, 0.2617939182541982, 0.23866603228752475, 0.2385427226570426, 0.2611522762211304, 0.2895330448334475, 0.2961001623379429, 0.2946632691340594, 0.2950910683017956, 0.30360451877606087, 0.3063412878467157, 0.31426010079359046, 0.3133447689858101, 0.3229263844996292, 0.3160068851235183, 0.32788626374063684, 0.33292840702781334, 0.3298958349574277, 0.31825439141842876, 0.313770938399697, 0.3128931093092042, 0.33042691632272714, 0.3226182291582567, 0.3360504437709926, 0.33384763612463664, 0.32228542845391644, 0.30445532548601806, 0.313281688947186, 0.3279527365516789, 0.34726895012197784, 0.33326872848258526, 0.3391131762571994, 0.3476426756612517, 0.35019096387634197, 0.36378412677326966, 0.38090206244472175, 0.38286733079318175, 0.3804779723537537, 0.38147890178822846, 0.3794076211654159, 0.39572597215310557, 0.3966766763784576, 0.4165169690579526, 0.4161375409595772, 0.42207266863383525, 0.4293791999181382, 0.4521954777999705, 0.4424734867894827, 0.4504417482291492]
[Sun Apr 19 20:24:25.792935 2020] [wsgi:error] [pid 13140:tid 139940363224832] [remote 127.0.0.1:37134] hello
[Sun Apr 19 20:24:26.701714 2020] [wsgi:error] [pid 13140:tid 139940363224832] [remote 127.0.0.1:37134] 
[Sun Apr 19 20:24:26.701746 2020] [wsgi:error] [pid 13140:tid 139940363224832] [remote 127.0.0.1:37134] Rows to drop:
[Sun Apr 19 20:24:26.701788 2020] [wsgi:error] [pid 13140:tid 139940363224832] [remote 127.0.0.1:37134]  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251]
[Sun Apr 19 20:24:26.703452 2020] [wsgi:error] [pid 13140:tid 139940363224832] [remote 127.0.0.1:37134] 
[Sun Apr 19 20:24:26.703469 2020] [wsgi:error] [pid 13140:tid 139940363224832] [remote 127.0.0.1:37134] df_anal:
[Sun Apr 19 20:24:26.748218 2020] [wsgi:error] [pid 13140:tid 139940363224832] [remote 127.0.0.1:37134]            Date  term_5  term_15  ...  ease_of_move  williams_r  rel_strength
[Sun Apr 19 20:24:26.748249 2020] [wsgi:error] [pid 13140:tid 139940363224832] [remote 127.0.0.1:37134] 43  2019-06-17     5.0      6.0  ...     30.846800  -10.935143     57.334465
[Sun Apr 19 20:24:26.748253 2020] [wsgi:error] [pid 13140:tid 139940363224832] [remote 127.0.0.1:37134] 44  2019-06-18     4.0      5.0  ...     80.071548   -6.129247     63.092304
[Sun Apr 19 20:24:26.748256 2020] [wsgi:error] [pid 13140:tid 139940363224832] [remote 127.0.0.1:37134] 45  2019-06-19     2.0      4.0  ...     10.280372   -8.061292     61.947182
[Sun Apr 19 20:24:26.748259 2020] [wsgi:error] [pid 13140:tid 139940363224832] [remote 127.0.0.1:37134] 46  2019-06-20     2.0      2.0  ...      8.694343   -3.790376     63.882477
[Sun Apr 19 20:24:26.748263 2020] [wsgi:error] [pid 13140:tid 139940363224832] [remote 127.0.0.1:37134] 47  2019-06-21     2.0      5.0  ...      1.016724   -7.861755     62.420357
[Sun Apr 19 20:24:26.748266 2020] [wsgi:error] [pid 13140:tid 139940363224832] [remote 127.0.0.1:37134] ..         ...     ...      ...  ...           ...         ...           ...
[Sun Apr 19 20:24:26.748269 2020] [wsgi:error] [pid 13140:tid 139940363224832] [remote 127.0.0.1:37134] 179 2019-12-30     5.0      6.0  ...    -43.295805   -8.715760     79.598984
[Sun Apr 19 20:24:26.748272 2020] [wsgi:error] [pid 13140:tid 139940363224832] [remote 127.0.0.1:37134] 180 2019-12-31     6.0      6.0  ...     43.581129   -1.200796     80.999276
[Sun Apr 19 20:24:26.748275 2020] [wsgi:error] [pid 13140:tid 139940363224832] [remote 127.0.0.1:37134] 181 2020-01-02     5.0      6.0  ...    100.424884   -0.751224     84.583749
[Sun Apr 19 20:24:26.748277 2020] [wsgi:error] [pid 13140:tid 139940363224832] [remote 127.0.0.1:37134] 182 2020-01-03     6.0      6.0  ...      7.183515  -10.684193     77.703728
[Sun Apr 19 20:24:26.748280 2020] [wsgi:error] [pid 13140:tid 139940363224832] [remote 127.0.0.1:37134] 183 2020-01-06     6.0      6.0  ...    -53.142315   -3.386960     79.183710
[Sun Apr 19 20:24:26.748290 2020] [wsgi:error] [pid 13140:tid 139940363224832] [remote 127.0.0.1:37134] 
[Sun Apr 19 20:24:26.748295 2020] [wsgi:error] [pid 13140:tid 139940363224832] [remote 127.0.0.1:37134] [141 rows x 9 columns]
[Sun Apr 19 20:24:26.748302 2020] [wsgi:error] [pid 13140:tid 139940363224832] [remote 127.0.0.1:37134] 
[Sun Apr 19 20:24:29.611039 2020] [wsgi:error] [pid 13140:tid 139940363224832] [remote 127.0.0.1:37134] {'dates': ['06/17/2019', '06/18/2019', '06/19/2019', '06/20/2019', '06/21/2019', '06/24/2019', '06/25/2019', '06/26/2019', '06/27/2019', '06/28/2019', '07/01/2019', '07/02/2019', '07/03/2019', '07/05/2019', '07/08/2019', '07/09/2019', '07/10/2019', '07/11/2019', '07/12/2019', '07/15/2019', '07/16/2019', '07/17/2019', '07/18/2019', '07/19/2019', '07/22/2019', '07/23/2019', '07/24/2019', '07/25/2019', '07/26/2019', '07/29/2019', '07/30/2019', '07/31/2019', '08/01/2019', '08/02/2019', '08/05/2019', '08/06/2019', '08/07/2019', '08/08/2019', '08/09/2019', '08/12/2019', '08/13/2019', '08/14/2019', '08/15/2019', '08/16/2019', '08/19/2019', '08/20/2019', '08/21/2019', '08/22/2019', '08/23/2019', '08/26/2019', '08/27/2019', '08/28/2019', '08/29/2019', '08/30/2019', '09/03/2019', '09/04/2019', '09/05/2019', '09/06/2019', '09/09/2019', '09/10/2019', '09/11/2019', '09/12/2019', '09/13/2019', '09/16/2019', '09/17/2019', '09/18/2019', '09/19/2019', '09/20/2019', '09/23/2019', '09/24/2019', '09/25/2019', '09/26/2019', '09/27/2019', '09/30/2019', '10/01/2019', '10/02/2019', '10/03/2019', '10/04/2019', '10/07/2019', '10/08/2019', '10/09/2019', '10/10/2019', '10/11/2019', '10/14/2019', '10/15/2019', '10/16/2019', '10/17/2019', '10/18/2019', '10/21/2019', '10/22/2019', '10/23/2019', '10/24/2019', '10/25/2019', '10/28/2019', '10/29/2019', '10/30/2019', '10/31/2019', '11/01/2019', '11/04/2019', '11/05/2019', '11/06/2019', '11/07/2019', '11/08/2019', '11/11/2019', '11/12/2019', '11/13/2019', '11/14/2019', '11/15/2019', '11/18/2019', '11/19/2019', '11/20/2019', '11/21/2019', '11/22/2019', '11/25/2019', '11/26/2019', '11/27/2019', '11/29/2019', '12/02/2019', '12/03/2019', '12/04/2019', '12/05/2019', '12/06/2019', '12/09/2019', '12/10/2019', '12/11/2019', '12/12/2019', '12/13/2019', '12/16/2019', '12/17/2019', '12/18/2019', '12/19/2019', '12/20/2019', '12/23/2019', '12/24/2019', '12/26/2019', '12/27/2019', '12/30/2019', '12/31/2019', '01/02/2020', '01/03/2020', '01/06/2020'], 'daily_ret': [0.0, 0.023518489865387605, -0.0029226505416980806, 0.008035578915449555, -0.0034092048531034133, -0.0010061374383740246, -0.015157619095578705, 0.02162908421537055, -0.00030030030030031167, -0.009111845399018832, 0.01834074373484248, 0.005854626643512668, 0.008286884032950264, -0.0008805831417249979, -0.020614013612103903, 0.0060993900609938945, 0.009888690121248165, -0.007282389411012104, 0.007682775712515546, 0.009394982784062944, -0.0034598703766873344, -0.005623471882640615, 0.011359724612736672, -0.014927550325780381, 0.02285404017967321, 0.007817778206736823, -0.0008140203026240946, -0.007907221929362043, 0.0034779248381798804, 0.009338596322325973, -0.0042922548645555406, 0.020404253280965567, -0.021639128802102822, -0.021158182603272065, -0.052347809038329605, 0.018930381710975466, 0.010355329949238538, 0.022055868167202647, -0.011994297792852566, -0.0025374396736156987, 0.04234836392657627, -0.02976503804373833, -0.004981504315659634, 0.023594725884802173, 0.018644067796610143, 4.753981459481496e-05, 0.010838562464346703, -0.0008465011286680701, -0.04622046502871139, 0.018999210422424116, -0.011283839411109556, 0.006710423197492185, 0.016931834768646865, -0.001291804219893698, -0.01456357190763639, 0.016966456003889203, 0.019551603805153226, -9.377344336088819e-05, 0.004267091812810638, 0.011813045711350802, 0.031795108444854704, -0.002258598327295476, -0.019432055046282842, 0.005257142857142883, 0.003638017280582005, 0.009379247847757234, -0.008124971944157662, -0.01461803041274447, 0.004546915905020021, -0.004754937820043856, 0.015389562660786449, -0.005157670904402184, -0.004866069398335501, 0.023535325838588823, 0.0027682278876635467, -0.02506790150941714, 0.008494702228717507, 0.02803188117018385, 0.0002202546143342204, -0.011714965207434144, 0.011720142602495523, 0.013478394925780743, 0.02659828762658092, -0.0014393971466068474, -0.0023317929367872615, -0.004037055923848329, 0.003882749498655957, 0.004802788167290018, 0.017342751998646395, -0.002286807201363698, 0.013418903150525083, 0.001644872111193378, 0.012316282124969208, 0.010017033011598665, -0.023127885966673437, -0.00012330963048214533, 0.02260955356408781, 0.028380768612317104, 0.006567117504495375, -0.0014368932038835128, 0.00042779916773621763, 0.008513450474265268, 0.0027367690706548184, 0.007918812946874769, -0.0009153318077803551, 0.009581615513819086, -0.006919499376110866, 0.011879378617118507, 0.005042143287176519, -0.0030325720703856317, -0.01164144353899892, -0.004483453018731741, -0.0008778290904927987, 0.017533807013522928, -0.007808687164470414, 0.013432214612735837, -0.0022028076463559403, -0.011562207670720206, -0.01783010296789838, 0.008826363461167934, 0.014671047604492912, 0.019316213570298953, -0.014000221639392576, 0.005844447774614125, 0.008529499404052307, 0.00254828821509029, 0.013593162896927717, 0.01711793567145207, 0.001965268348459985, -0.002389358439428037, 0.001000929434474772, -0.0020712806228125997, 0.016318350987689672, 0.0009507042253520487, 0.019840292679495, -0.0003794280983754049, 0.005935127674258007, 0.007306531284302949, 0.02281627788183227, -0.009721991010487816, 0.007968261439666492], 'cum_return': [0.0, 0.023518489865387605, 0.020595839323689524, 0.02863141823913908, 0.025222213386035666, 0.02421607594766164, 0.009058456852082935, 0.030687541067453486, 0.030387240767153174, 0.02127539536813434, 0.03961613910297682, 0.04547076574648949, 0.05375764977943975, 0.052877066637714756, 0.032263053025610854, 0.03836244308660475, 0.04825113320785291, 0.040968743796840804, 0.04865151950935635, 0.058046502293419296, 0.054586631916731965, 0.048963160034091346, 0.060322884646828015, 0.045395334321047635, 0.06824937450072084, 0.07606715270745766, 0.07525313240483357, 0.06734591047547153, 0.07082383531365141, 0.08016243163597739, 0.07587017677142185, 0.09627443005238742, 0.0746353012502846, 0.05347711864701253, 0.0011293096086829255, 0.02005969131965839, 0.03041502126889693, 0.05247088943609958, 0.04047659164324702, 0.03793915196963132, 0.08028751589620758, 0.05052247785246926, 0.04554097353680962, 0.0691356994216118, 0.08777976721822194, 0.08782730703281676, 0.09866586949716347, 0.09781936836849539, 0.051598903339784, 0.07059811376220812, 0.05931427435109857, 0.06602469754859075, 0.08295653231723761, 0.08166472809734392, 0.06710115618970752, 0.08406761219359672, 0.10361921599874994, 0.10352544255538905, 0.10779253436819969, 0.1196055800795505, 0.1514006885244052, 0.14914209019710972, 0.12971003515082688, 0.13496717800796976, 0.13860519528855175, 0.14798444313630899, 0.13985947119215134, 0.12524144077940685, 0.12978835668442687, 0.12503341886438302, 0.14042298152516947, 0.13526531062076727, 0.13039924122243177, 0.1539345670610206, 0.15670279494868414, 0.131634893439267, 0.1401295956679845, 0.16816147683816834, 0.16838173145250257, 0.15666676624506842, 0.16838690884756394, 0.18186530377334467, 0.2084635913999256, 0.20702419425331875, 0.2046924013165315, 0.20065534539268315, 0.20453809489133912, 0.20934088305862913, 0.22668363505727554, 0.22439682785591183, 0.2378157310064369, 0.2394606031176303, 0.2517768852425995, 0.2617939182541982, 0.23866603228752475, 0.2385427226570426, 0.2611522762211304, 0.2895330448334475, 0.2961001623379429, 0.2946632691340594, 0.2950910683017956, 0.30360451877606087, 0.3063412878467157, 0.31426010079359046, 0.3133447689858101, 0.3229263844996292, 0.3160068851235183, 0.32788626374063684, 0.33292840702781334, 0.3298958349574277, 0.31825439141842876, 0.313770938399697, 0.3128931093092042, 0.33042691632272714, 0.3226182291582567, 0.3360504437709926, 0.33384763612463664, 0.32228542845391644, 0.30445532548601806, 0.313281688947186, 0.3279527365516789, 0.34726895012197784, 0.33326872848258526, 0.3391131762571994, 0.3476426756612517, 0.35019096387634197, 0.36378412677326966, 0.38090206244472175, 0.38286733079318175, 0.3804779723537537, 0.38147890178822846, 0.3794076211654159, 0.39572597215310557, 0.3966766763784576, 0.4165169690579526, 0.4161375409595772, 0.42207266863383525, 0.4293791999181382, 0.4521954777999705, 0.4424734867894827, 0.4504417482291492]
[Sun Apr 19 20:25:05.243740 2020] [wsgi:error] [pid 13140:tid 139940455544576] [remote 127.0.0.1:41946] hello
[Sun Apr 19 20:25:06.158690 2020] [wsgi:error] [pid 13140:tid 139940455544576] [remote 127.0.0.1:41946] 
[Sun Apr 19 20:25:06.158727 2020] [wsgi:error] [pid 13140:tid 139940455544576] [remote 127.0.0.1:41946] Rows to drop:
[Sun Apr 19 20:25:06.158765 2020] [wsgi:error] [pid 13140:tid 139940455544576] [remote 127.0.0.1:41946]  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251]
[Sun Apr 19 20:25:06.160309 2020] [wsgi:error] [pid 13140:tid 139940455544576] [remote 127.0.0.1:41946] 
[Sun Apr 19 20:25:06.160325 2020] [wsgi:error] [pid 13140:tid 139940455544576] [remote 127.0.0.1:41946] df_anal:
[Sun Apr 19 20:25:06.200457 2020] [wsgi:error] [pid 13140:tid 139940455544576] [remote 127.0.0.1:41946]            Date  term_5  term_15  ...  ease_of_move  williams_r  rel_strength
[Sun Apr 19 20:25:06.200486 2020] [wsgi:error] [pid 13140:tid 139940455544576] [remote 127.0.0.1:41946] 43  2019-06-17     5.0      6.0  ...     30.846800  -10.935143     57.334465
[Sun Apr 19 20:25:06.200490 2020] [wsgi:error] [pid 13140:tid 139940455544576] [remote 127.0.0.1:41946] 44  2019-06-18     4.0      5.0  ...     80.071548   -6.129247     63.092304
[Sun Apr 19 20:25:06.200493 2020] [wsgi:error] [pid 13140:tid 139940455544576] [remote 127.0.0.1:41946] 45  2019-06-19     2.0      4.0  ...     10.280372   -8.061292     61.947182
[Sun Apr 19 20:25:06.200496 2020] [wsgi:error] [pid 13140:tid 139940455544576] [remote 127.0.0.1:41946] 46  2019-06-20     2.0      2.0  ...      8.694343   -3.790376     63.882477
[Sun Apr 19 20:25:06.200499 2020] [wsgi:error] [pid 13140:tid 139940455544576] [remote 127.0.0.1:41946] 47  2019-06-21     2.0      5.0  ...      1.016724   -7.861755     62.420357
[Sun Apr 19 20:25:06.200502 2020] [wsgi:error] [pid 13140:tid 139940455544576] [remote 127.0.0.1:41946] ..         ...     ...      ...  ...           ...         ...           ...
[Sun Apr 19 20:25:06.200505 2020] [wsgi:error] [pid 13140:tid 139940455544576] [remote 127.0.0.1:41946] 179 2019-12-30     5.0      6.0  ...    -43.295805   -8.715760     79.598984
[Sun Apr 19 20:25:06.200507 2020] [wsgi:error] [pid 13140:tid 139940455544576] [remote 127.0.0.1:41946] 180 2019-12-31     6.0      6.0  ...     43.581129   -1.200796     80.999276
[Sun Apr 19 20:25:06.200510 2020] [wsgi:error] [pid 13140:tid 139940455544576] [remote 127.0.0.1:41946] 181 2020-01-02     5.0      6.0  ...    100.424884   -0.751224     84.583749
[Sun Apr 19 20:25:06.200513 2020] [wsgi:error] [pid 13140:tid 139940455544576] [remote 127.0.0.1:41946] 182 2020-01-03     6.0      6.0  ...      7.183515  -10.684193     77.703728
[Sun Apr 19 20:25:06.200516 2020] [wsgi:error] [pid 13140:tid 139940455544576] [remote 127.0.0.1:41946] 183 2020-01-06     6.0      6.0  ...    -53.142315   -3.386960     79.183710
[Sun Apr 19 20:25:06.200518 2020] [wsgi:error] [pid 13140:tid 139940455544576] [remote 127.0.0.1:41946] 
[Sun Apr 19 20:25:06.200523 2020] [wsgi:error] [pid 13140:tid 139940455544576] [remote 127.0.0.1:41946] [141 rows x 9 columns]
[Sun Apr 19 20:25:06.200530 2020] [wsgi:error] [pid 13140:tid 139940455544576] [remote 127.0.0.1:41946] 
[Sun Apr 19 20:25:14.520018 2020] [wsgi:error] [pid 13139:tid 139940455544576] [remote 127.0.0.1:43108] hello
[Sun Apr 19 20:25:15.349695 2020] [wsgi:error] [pid 13139:tid 139940455544576] [remote 127.0.0.1:43108] 
[Sun Apr 19 20:25:15.349740 2020] [wsgi:error] [pid 13139:tid 139940455544576] [remote 127.0.0.1:43108] Rows to drop:
[Sun Apr 19 20:25:15.349786 2020] [wsgi:error] [pid 13139:tid 139940455544576] [remote 127.0.0.1:43108]  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251]
[Sun Apr 19 20:25:15.351298 2020] [wsgi:error] [pid 13139:tid 139940455544576] [remote 127.0.0.1:43108] 
[Sun Apr 19 20:25:15.351313 2020] [wsgi:error] [pid 13139:tid 139940455544576] [remote 127.0.0.1:43108] df_anal:
[Sun Apr 19 20:25:15.391479 2020] [wsgi:error] [pid 13139:tid 139940455544576] [remote 127.0.0.1:43108]            Date  term_5  term_15  ...  ease_of_move  williams_r  rel_strength
[Sun Apr 19 20:25:15.391512 2020] [wsgi:error] [pid 13139:tid 139940455544576] [remote 127.0.0.1:43108] 43  2019-06-17     5.0      6.0  ...     30.846800  -10.935143     57.334465
[Sun Apr 19 20:25:15.391516 2020] [wsgi:error] [pid 13139:tid 139940455544576] [remote 127.0.0.1:43108] 44  2019-06-18     4.0      5.0  ...     80.071548   -6.129247     63.092304
[Sun Apr 19 20:25:15.391519 2020] [wsgi:error] [pid 13139:tid 139940455544576] [remote 127.0.0.1:43108] 45  2019-06-19     2.0      4.0  ...     10.280372   -8.061292     61.947182
[Sun Apr 19 20:25:15.391522 2020] [wsgi:error] [pid 13139:tid 139940455544576] [remote 127.0.0.1:43108] 46  2019-06-20     2.0      2.0  ...      8.694343   -3.790376     63.882477
[Sun Apr 19 20:25:15.391525 2020] [wsgi:error] [pid 13139:tid 139940455544576] [remote 127.0.0.1:43108] 47  2019-06-21     2.0      5.0  ...      1.016724   -7.861755     62.420357
[Sun Apr 19 20:25:15.391528 2020] [wsgi:error] [pid 13139:tid 139940455544576] [remote 127.0.0.1:43108] ..         ...     ...      ...  ...           ...         ...           ...
[Sun Apr 19 20:25:15.391531 2020] [wsgi:error] [pid 13139:tid 139940455544576] [remote 127.0.0.1:43108] 179 2019-12-30     5.0      6.0  ...    -43.295805   -8.715760     79.598984
[Sun Apr 19 20:25:15.391533 2020] [wsgi:error] [pid 13139:tid 139940455544576] [remote 127.0.0.1:43108] 180 2019-12-31     6.0      6.0  ...     43.581129   -1.200796     80.999276
[Sun Apr 19 20:25:15.391536 2020] [wsgi:error] [pid 13139:tid 139940455544576] [remote 127.0.0.1:43108] 181 2020-01-02     5.0      6.0  ...    100.424884   -0.751224     84.583749
[Sun Apr 19 20:25:15.391539 2020] [wsgi:error] [pid 13139:tid 139940455544576] [remote 127.0.0.1:43108] 182 2020-01-03     6.0      6.0  ...      7.183515  -10.684193     77.703728
[Sun Apr 19 20:25:15.391542 2020] [wsgi:error] [pid 13139:tid 139940455544576] [remote 127.0.0.1:43108] 183 2020-01-06     6.0      6.0  ...    -53.142315   -3.386960     79.183710
[Sun Apr 19 20:25:15.391544 2020] [wsgi:error] [pid 13139:tid 139940455544576] [remote 127.0.0.1:43108] 
[Sun Apr 19 20:25:15.391549 2020] [wsgi:error] [pid 13139:tid 139940455544576] [remote 127.0.0.1:43108] [141 rows x 9 columns]
[Sun Apr 19 20:25:15.391555 2020] [wsgi:error] [pid 13139:tid 139940455544576] [remote 127.0.0.1:43108] 
[Sun Apr 19 20:30:10.771829 2020] [wsgi:error] [pid 13142:tid 139940360873728] [client 127.0.0.1:41946] Truncated or oversized response headers received from daemon process 'team128_app': /home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py
[Sun Apr 19 20:30:20.445405 2020] [wsgi:error] [pid 13142:tid 139940458186496] [client 127.0.0.1:43108] Truncated or oversized response headers received from daemon process 'team128_app': /home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py
[Sun Apr 19 20:45:34.347606 2020] [wsgi:error] [pid 13142:tid 139940466579200] [client 127.0.0.1:49910] Truncated or oversized response headers received from daemon process 'team128_app': /home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py
[Sun Apr 19 21:18:50.890782 2020] [wsgi:error] [pid 15550:tid 139940455544576] [remote 127.0.0.1:53290] Not Found: /api/api/analysis/example
[Sun Apr 19 21:21:07.877208 2020] [wsgi:error] [pid 15550:tid 139940363224832] [remote 127.0.0.1:45136] Not Found: /api/
[Sun Apr 19 21:21:09.819561 2020] [wsgi:error] [pid 15550:tid 139940455544576] [remote 127.0.0.1:45420] Not Found: /api/
[Sun Apr 19 21:23:25.100457 2020] [wsgi:error] [pid 13142:tid 139940360873728] [client 127.0.0.1:55852] Truncated or oversized response headers received from daemon process 'team128_app': /home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py, referer: http://localhost:5000/indicators
[Sun Apr 19 21:23:25.100845 2020] [wsgi:error] [pid 13142:tid 139940449793792] [client 127.0.0.1:48582] Truncated or oversized response headers received from daemon process 'team128_app': /home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py
[Sun Apr 19 21:46:51.156008 2020] [wsgi:error] [pid 15550:tid 139940363224832] [remote 127.0.0.1:49226] hello
[Sun Apr 19 21:46:51.960489 2020] [wsgi:error] [pid 15550:tid 139940363224832] [remote 127.0.0.1:49226] 
[Sun Apr 19 21:46:51.960533 2020] [wsgi:error] [pid 15550:tid 139940363224832] [remote 127.0.0.1:49226] Rows to drop:
[Sun Apr 19 21:46:51.960568 2020] [wsgi:error] [pid 15550:tid 139940363224832] [remote 127.0.0.1:49226]  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251]
[Sun Apr 19 21:46:51.962538 2020] [wsgi:error] [pid 15550:tid 139940363224832] [remote 127.0.0.1:49226] 
[Sun Apr 19 21:46:51.962567 2020] [wsgi:error] [pid 15550:tid 139940363224832] [remote 127.0.0.1:49226] df_anal:
[Sun Apr 19 21:46:52.002725 2020] [wsgi:error] [pid 15550:tid 139940363224832] [remote 127.0.0.1:49226]            Date  term_5  term_15  ...  ease_of_move  williams_r  rel_strength
[Sun Apr 19 21:46:52.002761 2020] [wsgi:error] [pid 15550:tid 139940363224832] [remote 127.0.0.1:49226] 43  2019-06-17     5.0      6.0  ...     30.846800  -10.935143     57.334465
[Sun Apr 19 21:46:52.002765 2020] [wsgi:error] [pid 15550:tid 139940363224832] [remote 127.0.0.1:49226] 44  2019-06-18     4.0      5.0  ...     80.071548   -6.129247     63.092304
[Sun Apr 19 21:46:52.002768 2020] [wsgi:error] [pid 15550:tid 139940363224832] [remote 127.0.0.1:49226] 45  2019-06-19     2.0      4.0  ...     10.280372   -8.061292     61.947182
[Sun Apr 19 21:46:52.002771 2020] [wsgi:error] [pid 15550:tid 139940363224832] [remote 127.0.0.1:49226] 46  2019-06-20     2.0      2.0  ...      8.694343   -3.790376     63.882477
[Sun Apr 19 21:46:52.002774 2020] [wsgi:error] [pid 15550:tid 139940363224832] [remote 127.0.0.1:49226] 47  2019-06-21     2.0      5.0  ...      1.016724   -7.861755     62.420357
[Sun Apr 19 21:46:52.002778 2020] [wsgi:error] [pid 15550:tid 139940363224832] [remote 127.0.0.1:49226] ..         ...     ...      ...  ...           ...         ...           ...
[Sun Apr 19 21:46:52.002781 2020] [wsgi:error] [pid 15550:tid 139940363224832] [remote 127.0.0.1:49226] 179 2019-12-30     5.0      6.0  ...    -43.295805   -8.715760     79.598984
[Sun Apr 19 21:46:52.002784 2020] [wsgi:error] [pid 15550:tid 139940363224832] [remote 127.0.0.1:49226] 180 2019-12-31     6.0      6.0  ...     43.581129   -1.200796     80.999276
[Sun Apr 19 21:46:52.002811 2020] [wsgi:error] [pid 15550:tid 139940363224832] [remote 127.0.0.1:49226] 181 2020-01-02     5.0      6.0  ...    100.424884   -0.751224     84.583749
[Sun Apr 19 21:46:52.002817 2020] [wsgi:error] [pid 15550:tid 139940363224832] [remote 127.0.0.1:49226] 182 2020-01-03     6.0      6.0  ...      7.183515  -10.684193     77.703728
[Sun Apr 19 21:46:52.002820 2020] [wsgi:error] [pid 15550:tid 139940363224832] [remote 127.0.0.1:49226] 183 2020-01-06     6.0      6.0  ...    -53.142315   -3.386960     79.183710
[Sun Apr 19 21:46:52.002822 2020] [wsgi:error] [pid 15550:tid 139940363224832] [remote 127.0.0.1:49226] 
[Sun Apr 19 21:46:52.002827 2020] [wsgi:error] [pid 15550:tid 139940363224832] [remote 127.0.0.1:49226] [141 rows x 9 columns]
[Sun Apr 19 21:46:52.002835 2020] [wsgi:error] [pid 15550:tid 139940363224832] [remote 127.0.0.1:49226] 
[Sun Apr 19 21:46:54.726765 2020] [wsgi:error] [pid 15550:tid 139940363224832] [remote 127.0.0.1:49226] {'dates': ['06/17/2019', '06/18/2019', '06/19/2019', '06/20/2019', '06/21/2019', '06/24/2019', '06/25/2019', '06/26/2019', '06/27/2019', '06/28/2019', '07/01/2019', '07/02/2019', '07/03/2019', '07/05/2019', '07/08/2019', '07/09/2019', '07/10/2019', '07/11/2019', '07/12/2019', '07/15/2019', '07/16/2019', '07/17/2019', '07/18/2019', '07/19/2019', '07/22/2019', '07/23/2019', '07/24/2019', '07/25/2019', '07/26/2019', '07/29/2019', '07/30/2019', '07/31/2019', '08/01/2019', '08/02/2019', '08/05/2019', '08/06/2019', '08/07/2019', '08/08/2019', '08/09/2019', '08/12/2019', '08/13/2019', '08/14/2019', '08/15/2019', '08/16/2019', '08/19/2019', '08/20/2019', '08/21/2019', '08/22/2019', '08/23/2019', '08/26/2019', '08/27/2019', '08/28/2019', '08/29/2019', '08/30/2019', '09/03/2019', '09/04/2019', '09/05/2019', '09/06/2019', '09/09/2019', '09/10/2019', '09/11/2019', '09/12/2019', '09/13/2019', '09/16/2019', '09/17/2019', '09/18/2019', '09/19/2019', '09/20/2019', '09/23/2019', '09/24/2019', '09/25/2019', '09/26/2019', '09/27/2019', '09/30/2019', '10/01/2019', '10/02/2019', '10/03/2019', '10/04/2019', '10/07/2019', '10/08/2019', '10/09/2019', '10/10/2019', '10/11/2019', '10/14/2019', '10/15/2019', '10/16/2019', '10/17/2019', '10/18/2019', '10/21/2019', '10/22/2019', '10/23/2019', '10/24/2019', '10/25/2019', '10/28/2019', '10/29/2019', '10/30/2019', '10/31/2019', '11/01/2019', '11/04/2019', '11/05/2019', '11/06/2019', '11/07/2019', '11/08/2019', '11/11/2019', '11/12/2019', '11/13/2019', '11/14/2019', '11/15/2019', '11/18/2019', '11/19/2019', '11/20/2019', '11/21/2019', '11/22/2019', '11/25/2019', '11/26/2019', '11/27/2019', '11/29/2019', '12/02/2019', '12/03/2019', '12/04/2019', '12/05/2019', '12/06/2019', '12/09/2019', '12/10/2019', '12/11/2019', '12/12/2019', '12/13/2019', '12/16/2019', '12/17/2019', '12/18/2019', '12/19/2019', '12/20/2019', '12/23/2019', '12/24/2019', '12/26/2019', '12/27/2019', '12/30/2019', '12/31/2019', '01/02/2020', '01/03/2020', '01/06/2020'], 'daily_ret': [0.0, 0.023518489865387605, -0.0029226505416980806, 0.008035578915449555, -0.0034092048531034133, -0.0010061374383740246, -0.015157619095578705, 0.02162908421537055, -0.00030030030030031167, -0.009111845399018832, 0.01834074373484248, 0.005854626643512668, 0.008286884032950264, -0.0008805831417249979, -0.020614013612103903, 0.0060993900609938945, 0.009888690121248165, -0.007282389411012104, 0.007682775712515546, 0.009394982784062944, -0.0034598703766873344, -0.005623471882640615, 0.011359724612736672, -0.014927550325780381, 0.02285404017967321, 0.007817778206736823, -0.0008140203026240946, -0.007907221929362043, 0.0034779248381798804, 0.009338596322325973, -0.0042922548645555406, 0.020404253280965567, -0.021639128802102822, -0.021158182603272065, -0.052347809038329605, 0.018930381710975466, 0.010355329949238538, 0.022055868167202647, -0.011994297792852566, -0.0025374396736156987, 0.04234836392657627, -0.02976503804373833, -0.004981504315659634, 0.023594725884802173, 0.018644067796610143, 4.753981459481496e-05, 0.010838562464346703, -0.0008465011286680701, -0.04622046502871139, 0.018999210422424116, -0.011283839411109556, 0.006710423197492185, 0.016931834768646865, -0.001291804219893698, -0.01456357190763639, 0.016966456003889203, 0.019551603805153226, -9.377344336088819e-05, 0.004267091812810638, 0.011813045711350802, 0.031795108444854704, -0.002258598327295476, -0.019432055046282842, 0.005257142857142883, 0.003638017280582005, 0.009379247847757234, -0.008124971944157662, -0.01461803041274447, 0.004546915905020021, -0.004754937820043856, 0.015389562660786449, -0.005157670904402184, -0.004866069398335501, 0.023535325838588823, 0.0027682278876635467, -0.02506790150941714, 0.008494702228717507, 0.02803188117018385, 0.0002202546143342204, -0.011714965207434144, 0.011720142602495523, 0.013478394925780743, 0.02659828762658092, -0.0014393971466068474, -0.0023317929367872615, -0.004037055923848329, 0.003882749498655957, 0.004802788167290018, 0.017342751998646395, -0.002286807201363698, 0.013418903150525083, 0.001644872111193378, 0.012316282124969208, 0.010017033011598665, -0.023127885966673437, -0.00012330963048214533, 0.02260955356408781, 0.028380768612317104, 0.006567117504495375, -0.0014368932038835128, 0.00042779916773621763, 0.008513450474265268, 0.0027367690706548184, 0.007918812946874769, -0.0009153318077803551, 0.009581615513819086, -0.006919499376110866, 0.011879378617118507, 0.005042143287176519, -0.0030325720703856317, -0.01164144353899892, -0.004483453018731741, -0.0008778290904927987, 0.017533807013522928, -0.007808687164470414, 0.013432214612735837, -0.0022028076463559403, -0.011562207670720206, -0.01783010296789838, 0.008826363461167934, 0.014671047604492912, 0.019316213570298953, -0.014000221639392576, 0.005844447774614125, 0.008529499404052307, 0.00254828821509029, 0.013593162896927717, 0.01711793567145207, 0.001965268348459985, -0.002389358439428037, 0.001000929434474772, -0.0020712806228125997, 0.016318350987689672, 0.0009507042253520487, 0.019840292679495, -0.0003794280983754049, 0.005935127674258007, 0.007306531284302949, 0.02281627788183227, -0.009721991010487816, 0.007968261439666492], 'cum_return': [0.0, 0.023518489865387605, 0.020595839323689524, 0.02863141823913908, 0.025222213386035666, 0.02421607594766164, 0.009058456852082935, 0.030687541067453486, 0.030387240767153174, 0.02127539536813434, 0.03961613910297682, 0.04547076574648949, 0.05375764977943975, 0.052877066637714756, 0.032263053025610854, 0.03836244308660475, 0.04825113320785291, 0.040968743796840804, 0.04865151950935635, 0.058046502293419296, 0.054586631916731965, 0.048963160034091346, 0.060322884646828015, 0.045395334321047635, 0.06824937450072084, 0.07606715270745766, 0.07525313240483357, 0.06734591047547153, 0.07082383531365141, 0.08016243163597739, 0.07587017677142185, 0.09627443005238742, 0.0746353012502846, 0.05347711864701253, 0.0011293096086829255, 0.02005969131965839, 0.03041502126889693, 0.05247088943609958, 0.04047659164324702, 0.03793915196963132, 0.08028751589620758, 0.05052247785246926, 0.04554097353680962, 0.0691356994216118, 0.08777976721822194, 0.08782730703281676, 0.09866586949716347, 0.09781936836849539, 0.051598903339784, 0.07059811376220812, 0.05931427435109857, 0.06602469754859075, 0.08295653231723761, 0.08166472809734392, 0.06710115618970752, 0.08406761219359672, 0.10361921599874994, 0.10352544255538905, 0.10779253436819969, 0.1196055800795505, 0.1514006885244052, 0.14914209019710972, 0.12971003515082688, 0.13496717800796976, 0.13860519528855175, 0.14798444313630899, 0.13985947119215134, 0.12524144077940685, 0.12978835668442687, 0.12503341886438302, 0.14042298152516947, 0.13526531062076727, 0.13039924122243177, 0.1539345670610206, 0.15670279494868414, 0.131634893439267, 0.1401295956679845, 0.16816147683816834, 0.16838173145250257, 0.15666676624506842, 0.16838690884756394, 0.18186530377334467, 0.2084635913999256, 0.20702419425331875, 0.2046924013165315, 0.20065534539268315, 0.20453809489133912, 0.20934088305862913, 0.22668363505727554, 0.22439682785591183, 0.2378157310064369, 0.2394606031176303, 0.2517768852425995, 0.2617939182541982, 0.23866603228752475, 0.2385427226570426, 0.2611522762211304, 0.2895330448334475, 0.2961001623379429, 0.2946632691340594, 0.2950910683017956, 0.30360451877606087, 0.3063412878467157, 0.31426010079359046, 0.3133447689858101, 0.3229263844996292, 0.3160068851235183, 0.32788626374063684, 0.33292840702781334, 0.3298958349574277, 0.31825439141842876, 0.313770938399697, 0.3128931093092042, 0.33042691632272714, 0.3226182291582567, 0.3360504437709926, 0.33384763612463664, 0.32228542845391644, 0.30445532548601806, 0.313281688947186, 0.3279527365516789, 0.34726895012197784, 0.33326872848258526, 0.3391131762571994, 0.3476426756612517, 0.35019096387634197, 0.36378412677326966, 0.38090206244472175, 0.38286733079318175, 0.3804779723537537, 0.38147890178822846, 0.3794076211654159, 0.39572597215310557, 0.3966766763784576, 0.4165169690579526, 0.4161375409595772, 0.42207266863383525, 0.4293791999181382, 0.4521954777999705, 0.4424734867894827, 0.4504417482291492]
[Sun Apr 19 21:50:13.983563 2020] [wsgi:error] [pid 15550:tid 139940455544576] [remote 127.0.0.1:46444] hello
[Sun Apr 19 21:50:14.979947 2020] [wsgi:error] [pid 15550:tid 139940455544576] [remote 127.0.0.1:46444] 
[Sun Apr 19 21:50:14.980007 2020] [wsgi:error] [pid 15550:tid 139940455544576] [remote 127.0.0.1:46444] Rows to drop:
[Sun Apr 19 21:50:14.980092 2020] [wsgi:error] [pid 15550:tid 139940455544576] [remote 127.0.0.1:46444]  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251]
[Sun Apr 19 21:50:14.983051 2020] [wsgi:error] [pid 15550:tid 139940455544576] [remote 127.0.0.1:46444] 
[Sun Apr 19 21:50:14.983073 2020] [wsgi:error] [pid 15550:tid 139940455544576] [remote 127.0.0.1:46444] df_anal:
[Sun Apr 19 21:50:15.032638 2020] [wsgi:error] [pid 15550:tid 139940455544576] [remote 127.0.0.1:46444]            Date  term_5  term_15  ...  ease_of_move  williams_r  rel_strength
[Sun Apr 19 21:50:15.032681 2020] [wsgi:error] [pid 15550:tid 139940455544576] [remote 127.0.0.1:46444] 43  2019-06-17     5.0      6.0  ...     30.846800  -10.935143     57.334465
[Sun Apr 19 21:50:15.032685 2020] [wsgi:error] [pid 15550:tid 139940455544576] [remote 127.0.0.1:46444] 44  2019-06-18     4.0      5.0  ...     80.071548   -6.129247     63.092304
[Sun Apr 19 21:50:15.032688 2020] [wsgi:error] [pid 15550:tid 139940455544576] [remote 127.0.0.1:46444] 45  2019-06-19     2.0      4.0  ...     10.280372   -8.061292     61.947182
[Sun Apr 19 21:50:15.032691 2020] [wsgi:error] [pid 15550:tid 139940455544576] [remote 127.0.0.1:46444] 46  2019-06-20     2.0      2.0  ...      8.694343   -3.790376     63.882477
[Sun Apr 19 21:50:15.032694 2020] [wsgi:error] [pid 15550:tid 139940455544576] [remote 127.0.0.1:46444] 47  2019-06-21     2.0      5.0  ...      1.016724   -7.861755     62.420357
[Sun Apr 19 21:50:15.032697 2020] [wsgi:error] [pid 15550:tid 139940455544576] [remote 127.0.0.1:46444] ..         ...     ...      ...  ...           ...         ...           ...
[Sun Apr 19 21:50:15.032700 2020] [wsgi:error] [pid 15550:tid 139940455544576] [remote 127.0.0.1:46444] 179 2019-12-30     5.0      6.0  ...    -43.295805   -8.715760     79.598984
[Sun Apr 19 21:50:15.032702 2020] [wsgi:error] [pid 15550:tid 139940455544576] [remote 127.0.0.1:46444] 180 2019-12-31     6.0      6.0  ...     43.581129   -1.200796     80.999276
[Sun Apr 19 21:50:15.032705 2020] [wsgi:error] [pid 15550:tid 139940455544576] [remote 127.0.0.1:46444] 181 2020-01-02     5.0      6.0  ...    100.424884   -0.751224     84.583749
[Sun Apr 19 21:50:15.032708 2020] [wsgi:error] [pid 15550:tid 139940455544576] [remote 127.0.0.1:46444] 182 2020-01-03     6.0      6.0  ...      7.183515  -10.684193     77.703728
[Sun Apr 19 21:50:15.032711 2020] [wsgi:error] [pid 15550:tid 139940455544576] [remote 127.0.0.1:46444] 183 2020-01-06     6.0      6.0  ...    -53.142315   -3.386960     79.183710
[Sun Apr 19 21:50:15.032728 2020] [wsgi:error] [pid 15550:tid 139940455544576] [remote 127.0.0.1:46444] 
[Sun Apr 19 21:50:15.032733 2020] [wsgi:error] [pid 15550:tid 139940455544576] [remote 127.0.0.1:46444] [141 rows x 9 columns]
[Sun Apr 19 21:50:15.032741 2020] [wsgi:error] [pid 15550:tid 139940455544576] [remote 127.0.0.1:46444] 
[Sun Apr 19 21:55:03.529749 2020] [wsgi:error] [pid 13142:tid 139940458186496] [client 127.0.0.1:45336] Truncated or oversized response headers received from daemon process 'team128_app': /home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py
[Sun Apr 19 21:55:19.808522 2020] [wsgi:error] [pid 13142:tid 139940466579200] [client 127.0.0.1:46444] Truncated or oversized response headers received from daemon process 'team128_app': /home/dvateam128/webapps/team128_app/myproject/myproject/wsgi.py
